use anyhow::Result;
use cainome_parser::tokens::Token;
use cainome_parser::{AbiParser, Error, ParserContext, TypeRegistry};
use camino::Utf8PathBuf;
use proc_macro2::TokenStream;
use std::collections::HashMap;
use std::fmt;
use std::fs;
use std::io;

mod execution_version;
pub mod expand;
pub use execution_version::{ExecutionVersion, ParseExecutionVersionError};

#[cfg(test)]
mod generation_tests;

use crate::expand::contract::Contract;
use crate::expand::{Expandable, ExpansionContext, ExpansionContextFactory, Module};
// use crate::expand::{CairoContract, CairoEnum, CairoEnumEvent, CairoFunction, CairoStruct};

///Type-safe contract bindings generated by Abigen.
#[derive(Clone)]
pub struct ContractBindings {
    /// Name of the contract.
    pub name: String,
    /// Tokenized ABI written to a `[TokenStream2]`.
    pub tokens: TokenStream,
}

impl ContractBindings {
    /// Writes the bindings to the specified file.
    ///
    /// # Arguments
    ///
    /// * `file` - The path to the file to write the bindings to.
    pub fn write_to_file(&self, file: &str) -> io::Result<()> {
        let content = format!(
            "// ****\n// Auto-generated by cainome do not edit.\n// ****\n\n#![allow(clippy::all)]\n#![allow(warnings)]\n#![rustfmt::skip]\n\n{self}",
        );
        fs::write(file, content)
    }
}

impl fmt::Display for ContractBindings {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let syntax_tree = syn::parse2::<syn::File>(self.tokens.clone()).unwrap();
        let s = prettyplease::unparse(&syntax_tree);
        f.write_str(&s)
    }
}

impl fmt::Debug for ContractBindings {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("ContractBindings")
            .field("name", &self.name)
            .finish()
    }
}

/// Programmatically generate type-safe Rust bindings for an Starknet smart contract from its ABI.
///
/// Currently only one contract at a time is supported.
#[derive(Debug, Clone)]
pub struct Abigen {
    /// Name of the contract, used as the variable name in the generated code
    /// to identify the contract.
    pub contract_name: String,
    /// The path to a sierra artifact or a JSON with ABI entries only.
    pub abi_source: Utf8PathBuf,
    /// Types aliases to avoid name conflicts, as for now the types are limited to the
    /// latest segment of the fully qualified path.
    pub types_aliases: HashMap<String, String>,
    /// The version of transaction to be executed.
    pub execution_version: ExecutionVersion,
    /// Derives to be added to the generated types.
    pub derives: Vec<String>,
    /// Derives to be added to the generated contract.
    pub contract_derives: Vec<String>,
    /// Types to be skipped from the generated types, usually combined with the `types_aliases` to
    /// let the user specify the implementation of the types. If a type is generic, the generic arguments
    /// are not part of the compared name.
    pub type_skips: Vec<String>,

    /// Optional path to the contract source code.
    /// If provided, declare and deploy methods will be added to contract definition.
    pub contract_source: Option<String>,

    pub add_declaration: bool,
    pub add_deployment: bool,
}

impl Abigen {
    /// Creates a new instance of `Abigen`.
    ///
    /// # Arguments
    ///
    /// * `contract_name` - Name of the contract, used as the variable name in the generated code
    ///   to identify the contract.
    /// * `abi_source` - The path to a sierra artifact or a JSON with ABI entries only.
    pub fn new(contract_name: &str, abi_source: &str) -> Self {
        Self {
            contract_name: contract_name.to_string(),
            abi_source: Utf8PathBuf::from(abi_source),
            types_aliases: HashMap::new(),
            execution_version: ExecutionVersion::V3,
            derives: vec![],
            contract_derives: vec![],
            type_skips: vec![],
            contract_source: None,
            add_declaration: true,
            add_deployment: true,
        }
    }

    /// Sets the types aliases to avoid name conflicts.
    ///
    /// # Arguments
    ///
    /// * `types_aliases` - Types aliases to avoid name conflicts.
    pub fn with_types_aliases(mut self, types_aliases: HashMap<String, String>) -> Self {
        self.types_aliases = types_aliases;
        self
    }

    /// Sets the execution version to be used.
    ///
    /// # Arguments
    ///
    /// * `execution_version` - The version of transaction to be executed.
    pub fn with_execution_version(mut self, execution_version: ExecutionVersion) -> Self {
        self.execution_version = execution_version;
        self
    }

    /// Sets the derives to be added to the generated types.
    ///
    /// # Arguments
    ///
    /// * `derives` - Derives to be added to the generated types.
    pub fn with_derives(mut self, derives: Vec<String>) -> Self {
        self.derives = derives;
        self
    }

    /// Sets the derives to be added to the generated contract.
    ///
    /// # Arguments
    ///
    /// * `derives` - Derives to be added to the generated contract.
    pub fn with_contract_derives(mut self, derives: Vec<String>) -> Self {
        self.contract_derives = derives;
        self
    }

    /// Sets the types to be skipped from the generated types.
    ///
    /// # Arguments
    ///
    /// * `type_skips` - Types to be skipped from the generated types.
    pub fn with_type_skips(mut self, type_skips: Vec<String>) -> Self {
        self.type_skips = type_skips;
        self
    }

    pub fn with_add_declaration(mut self, add_declare: bool) -> Self {
        self.add_declaration = add_declare;
        self
    }

    pub fn with_add_deployment(mut self, add_deploy: bool) -> Self {
        self.add_deployment = add_deploy;
        self
    }

    /// Generates the contract bindings.
    pub fn generate(self) -> Result<ContractBindings, Error> {
        let file_content = std::fs::read_to_string(&self.abi_source)?;

        let entries = AbiParser::parse_abi_string(&file_content).map_err(|e| {
            Error::ParsingFailed(format!(
                "Abi source {} could not be parsed {:?}. ABI file should be 
                a JSON with an array of abi entries or a Sierra artifact.",
                self.abi_source, e
            ))
        })?;

        let ctx = ExpansionContextFactory::new(&self.abi_source)
            .with_contract_derives(self.contract_derives)
            .with_derives(self.derives)
            .with_execution(self.execution_version)
            .with_aliases(self.types_aliases)
            .with_type_skips(self.type_skips)
            .with_contract_name(&self.contract_name)
            .with_add_declaration(self.add_declaration)
            .with_add_deployment(self.add_deployment)
            .build();

        let registry =
            AbiParser::build_registry(entries, ParserContext::from(&ctx)).map_err(|e| {
                Error::ParsingFailed(format!("Abi source {} could not be parsed {:?}. ABI seems to have incorrect structure.",
                    self.abi_source, e
                ))
            })?;

        let expanded = abi_to_tokenstream(&registry, &ctx)
            .map_err(|e| Error::ExpansionFailed(format!("{e}")))?;

        Ok(ContractBindings {
            name: self.contract_name,
            tokens: expanded,
        })
    }
}

/// Converts the given ABI (in it's tokenize form) into rust bindings.
///
/// # Arguments
///
/// * `contract_name` - Name of the contract.
/// * `abi_tokens` - Tokenized ABI.
/// * `execution_version` - The version of transaction to be executed.
/// * `derives` - Derives to be added to the generated types.
/// * `contract_derives` - Derives to be added to the generated contract.
/// * `type_skips` - Types to be skipped from the generated types.
pub fn abi_to_tokenstream(
    registry: &TypeRegistry,
    ctx: &ExpansionContext,
) -> Result<TokenStream, Box<dyn std::error::Error + 'static>> {
    tracing::trace!("Starting ABI to TokenStream expansion");

    let contract = Contract::new(
        &ctx.contract_name,
        ctx.contract_derives.iter().cloned().collect(),
        registry,
    );

    let mut root = Module::new().with_includes(contract.expand(ctx))?;

    let registered_structs = registry.get_structs();
    let registered_enums = registry.get_enums();
    let registered_events = registry.get_events();

    for r#struct in registered_structs {
        tracing::trace!("Expanding struct: {:?}", r#struct.borrow());

        let Token::Struct(s) = &*r#struct.borrow() else {
            unreachable!("Expected only Struct tokens in the collection, found something else.");
        };

        root.include_many(s.expand(ctx))?;
    }

    for enumeration in registered_enums {
        tracing::trace!("Expanding enum: {:?}", enumeration.borrow());

        let Token::Enum(e) = &*enumeration.borrow() else {
            unreachable!("Expected only Enum tokens in the collection, found something else.");
        };

        root.include_many(e.expand(ctx))?;
    }

    for event in registered_events {
        tracing::trace!("Expanding event: {:?}", event.borrow());

        let Token::Event(e) = &*event.borrow() else {
            unreachable!("Expected only Event tokens in the collection, found something else.");
        };

        root.include_many(e.expand(ctx))?;
    }

    tracing::trace!("Root module expansion started.");
    Ok(root.token_stream())
}

mod zzz {
    pub mod my {
        pub enum Nested<A> {
            One(A),
            Two((starknet::core::types::Felt, starknet::core::types::Felt)),
        }
        impl<A> cainome_cairo_serde::CairoSerde for Nested<A>
        where
            A: cainome_cairo_serde::CairoSerde<RustType = A>,
        {
            type RustType = Self;
            const SERIALIZED_SIZE: std::option::Option<usize> = std::option::Option::None;
            #[inline]
            fn cairo_serialized_size(__rust: &Self::RustType) -> usize {
                match __rust { Nested :: One (val) => A :: cairo_serialized_size (val) + 1 , Nested :: Two (val) => < (starknet :: core :: types :: Felt , starknet :: core :: types :: Felt) > :: cairo_serialized_size (val) + 1 , _ => 0 }
            }
            fn cairo_serialize(__rust: &Self::RustType) -> Vec<starknet::core::types::Felt> {
                match __rust {
                    Nested::One(val) => {
                        let mut temp = vec![];
                        temp.extend(usize::cairo_serialize(&0usize));
                        temp.extend(A::cairo_serialize(val));
                        temp
                    }
                    Nested::Two(val) => {
                        let mut temp = vec![];
                        temp.extend(usize::cairo_serialize(&1usize));
                        temp . extend (< (starknet :: core :: types :: Felt , starknet :: core :: types :: Felt) > :: cairo_serialize (val)) ;
                        temp
                    }
                    _ => vec![],
                }
            }
            fn cairo_deserialize(
                __felts: &[starknet::core::types::Felt],
                __offset: usize,
            ) -> cainome_cairo_serde::Result<Self::RustType> {
                let __f = __felts[__offset];
                let __index = u128::from_be_bytes(__f.to_bytes_be()[16..].try_into().unwrap());
                match __index as usize {
                    0usize => Ok(Nested::One(A::cairo_deserialize(__felts, __offset + 1)?)),
                    1usize => Ok(Nested::Two(<(
                        starknet::core::types::Felt,
                        starknet::core::types::Felt,
                    )>::cairo_deserialize(
                        __felts, __offset + 1
                    )?)),
                    _ => {
                        return Err(cainome_cairo_serde::Error::Deserialize(format!(
                            "Index not handle for enum {}",
                            "Nested"
                        )))
                    }
                }
            }
        }
        pub struct Var {
            pub a: starknet::core::types::Felt,
            pub nested: Nested<starknet::core::types::Felt>,
        }
        impl cainome_cairo_serde::CairoSerde for Var {
            type RustType = Self;
            const SERIALIZED_SIZE: std::option::Option<usize> = None;
            #[inline]
            fn cairo_serialized_size(__rust: &Self::RustType) -> usize {
                let mut __size = 0;
                __size += starknet::core::types::Felt::cairo_serialized_size(&__rust.a);
                __size += Nested::cairo_serialized_size(&__rust.nested);
                __size
            }
            fn cairo_serialize(__rust: &Self::RustType) -> Vec<starknet::core::types::Felt> {
                let mut __out: Vec<starknet::core::types::Felt> = vec![];
                __out.extend(starknet::core::types::Felt::cairo_serialize(&__rust.a));
                __out.extend(Nested::cairo_serialize(&__rust.nested));
                __out
            }
            fn cairo_deserialize(
                __felts: &[starknet::core::types::Felt],
                __offset: usize,
            ) -> cainome_cairo_serde::Result<Self::RustType> {
                let mut __offset = __offset;
                let a = starknet::core::types::Felt::cairo_deserialize(__felts, __offset)?;
                __offset += starknet::core::types::Felt::cairo_serialized_size(&a);
                let nested = Nested::cairo_deserialize(__felts, __offset)?;
                __offset += Nested::cairo_serialized_size(&nested);
                Ok(Var { a, nested })
            }
        }
    }
    pub struct Contract<A: starknet::accounts::ConnectedAccount + Sync> {
        pub address: starknet::core::types::Felt,
        pub account: A,
        pub block_id: starknet::core::types::BlockId,
    }
    impl<A: starknet::accounts::ConnectedAccount + Sync> Contract<A> {
        pub fn new(address: starknet::core::types::Felt, account: A) -> Self {
            Self {
                address,
                account,
                block_id: starknet::core::types::BlockId::Tag(
                    starknet::core::types::BlockTag::PreConfirmed,
                ),
            }
        }
        pub fn set_contract_address(&mut self, address: starknet::core::types::Felt) {
            self.address = address;
        }
        pub fn provider(&self) -> &A::Provider {
            self.account.provider()
        }
        pub fn set_block(&mut self, block_id: starknet::core::types::BlockId) {
            self.block_id = block_id;
        }
        pub fn with_block(self, block_id: starknet::core::types::BlockId) -> Self {
            Self { block_id, ..self }
        }
    }
    pub struct ContractReader<P: starknet::providers::Provider + Sync> {
        pub address: starknet::core::types::Felt,
        pub provider: P,
        pub block_id: starknet::core::types::BlockId,
    }
    impl<P: starknet::providers::Provider + Sync> ContractReader<P> {
        pub fn new(address: starknet::core::types::Felt, provider: P) -> Self {
            Self {
                address,
                provider,
                block_id: starknet::core::types::BlockId::Tag(
                    starknet::core::types::BlockTag::PreConfirmed,
                ),
            }
        }
        pub fn set_contract_address(&mut self, address: starknet::core::types::Felt) {
            self.address = address;
        }
        pub fn provider(&self) -> &P {
            &self.provider
        }
        pub fn set_block(&mut self, block_id: starknet::core::types::BlockId) {
            self.block_id = block_id;
        }
        pub fn with_block(self, block_id: starknet::core::types::BlockId) -> Self {
            Self { block_id, ..self }
        }
    }
}
