use anyhow::Result;
use cainome_parser::tokens::{StateMutability, Token};
use cainome_parser::{AbiParser, TokenizedAbi};
use camino::Utf8PathBuf;
use proc_macro2::TokenStream;
use quote::quote;
use std::collections::HashMap;
use std::fmt;
use std::fs;
use std::io;

mod execution_version;
mod expand;
pub use execution_version::{ExecutionVersion, ParseExecutionVersionError};

use crate::expand::contract::CairoContract;
use crate::expand::{utils, Expandable, ExpansionContext};
// use crate::expand::{CairoContract, CairoEnum, CairoEnumEvent, CairoFunction, CairoStruct};

///Type-safe contract bindings generated by Abigen.
#[derive(Clone)]
pub struct ContractBindings {
    /// Name of the contract.
    pub name: String,
    /// Tokenized ABI written to a `[TokenStream2]`.
    pub tokens: TokenStream,
}

impl ContractBindings {
    /// Writes the bindings to the specified file.
    ///
    /// # Arguments
    ///
    /// * `file` - The path to the file to write the bindings to.
    pub fn write_to_file(&self, file: &str) -> io::Result<()> {
        let content = format!(
            "// ****\n// Auto-generated by cainome do not edit.\n// ****\n\n#![allow(clippy::all)]\n#![allow(warnings)]\n\n{}",
            self
        );
        fs::write(file, content)
    }
}

impl fmt::Display for ContractBindings {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let syntax_tree = syn::parse2::<syn::File>(self.tokens.clone()).unwrap();
        let s = prettyplease::unparse(&syntax_tree);
        f.write_str(&s)
    }
}

impl fmt::Debug for ContractBindings {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("ContractBindings")
            .field("name", &self.name)
            .finish()
    }
}

/// Programmatically generate type-safe Rust bindings for an Starknet smart contract from its ABI.
///
/// Currently only one contract at a time is supported.
#[derive(Debug, Clone)]
pub struct Abigen {
    /// Name of the contract, used as the variable name in the generated code
    /// to identify the contract.
    pub contract_name: String,
    /// The path to a sierra artifact or a JSON with ABI entries only.
    pub abi_source: Utf8PathBuf,
    /// Types aliases to avoid name conflicts, as for now the types are limited to the
    /// latest segment of the fully qualified path.
    pub types_aliases: HashMap<String, String>,
    /// The version of transaction to be executed.
    pub execution_version: ExecutionVersion,
    /// Derives to be added to the generated types.
    pub derives: Vec<String>,
    /// Derives to be added to the generated contract.
    pub contract_derives: Vec<String>,
    /// Types to be skipped from the generated types, usually combined with the `types_aliases` to
    /// let the user specify the implementation of the types. If a type is generic, the generic arguments
    /// are not part of the compared name.
    pub type_skips: Vec<String>,
}

impl Abigen {
    /// Creates a new instance of `Abigen`.
    ///
    /// # Arguments
    ///
    /// * `contract_name` - Name of the contract, used as the variable name in the generated code
    ///   to identify the contract.
    /// * `abi_source` - The path to a sierra artifact or a JSON with ABI entries only.
    pub fn new(contract_name: &str, abi_source: &str) -> Self {
        Self {
            contract_name: contract_name.to_string(),
            abi_source: Utf8PathBuf::from(abi_source),
            types_aliases: HashMap::new(),
            execution_version: ExecutionVersion::V1,
            derives: vec![],
            contract_derives: vec![],
            type_skips: vec![],
        }
    }

    /// Sets the types aliases to avoid name conflicts.
    ///
    /// # Arguments
    ///
    /// * `types_aliases` - Types aliases to avoid name conflicts.
    pub fn with_types_aliases(mut self, types_aliases: HashMap<String, String>) -> Self {
        self.types_aliases = types_aliases;
        self
    }

    /// Sets the execution version to be used.
    ///
    /// # Arguments
    ///
    /// * `execution_version` - The version of transaction to be executed.
    pub fn with_execution_version(mut self, execution_version: ExecutionVersion) -> Self {
        self.execution_version = execution_version;
        self
    }

    /// Sets the derives to be added to the generated types.
    ///
    /// # Arguments
    ///
    /// * `derives` - Derives to be added to the generated types.
    pub fn with_derives(mut self, derives: Vec<String>) -> Self {
        self.derives = derives;
        self
    }

    /// Sets the derives to be added to the generated contract.
    ///
    /// # Arguments
    ///
    /// * `derives` - Derives to be added to the generated contract.
    pub fn with_contract_derives(mut self, derives: Vec<String>) -> Self {
        self.contract_derives = derives;
        self
    }

    /// Sets the types to be skipped from the generated types.
    ///
    /// # Arguments
    ///
    /// * `type_skips` - Types to be skipped from the generated types.
    pub fn with_type_skips(mut self, type_skips: Vec<String>) -> Self {
        self.type_skips = type_skips;
        self
    }
    /// Generates the contract bindings.
    pub fn generate(&self) -> Result<ContractBindings> {
        let file_content = std::fs::read_to_string(&self.abi_source)?;

        match AbiParser::tokens_from_abi_string(&file_content, &self.types_aliases) {
            Ok(tokens) => {
                let expanded = abi_to_tokenstream(
                    &tokens,
                    &self.contract_name,
                    self.execution_version,
                    &self.derives,
                    &self.contract_derives,
                    &self.type_skips,
                );

                Ok(ContractBindings {
                    name: self.contract_name.clone(),
                    tokens: expanded,
                })
            }
            Err(e) => {
                anyhow::bail!(
                    "Abi source {} could not be parsed {:?}. ABI file should be a JSON with an array of abi entries or a Sierra artifact.",
                    self.abi_source, e
                )
            }
        }
    }
}

/// Converts the given ABI (in it's tokenize form) into rust bindings.
///
/// # Arguments
///
/// * `contract_name` - Name of the contract.
/// * `abi_tokens` - Tokenized ABI.
/// * `execution_version` - The version of transaction to be executed.
/// * `derives` - Derives to be added to the generated types.
/// * `contract_derives` - Derives to be added to the generated contract.
/// * `type_skips` - Types to be skipped from the generated types.
pub fn abi_to_tokenstream(
    abi_tokens: &TokenizedAbi,
    contract_name: &str,
    execution_version: ExecutionVersion,
    derives: &[String],
    contract_derives: &[String],
    type_skips: &[String],
) -> TokenStream {
    let contract = CairoContract::new(contract_name, contract_derives.into(), abi_tokens);

    let ctx = ExpansionContext {
        contract_name: contract_name.to_string(),
        derives: derives.to_vec(),
        execution_version: execution_version,
        type_param: None,
    };

    let mut tokens: Vec<TokenStream> = contract.expand(&ctx);

    let sorted_structs = abi_tokens.structs.clone();
    let sorted_enums = abi_tokens.enums.clone();

    for structs in &sorted_structs {
        let Token::Struct(s) = &*structs.borrow() else {
            // TODO: log
            continue;
        };
        let mut expanded = s.expand(&ctx);
        tokens.append(&mut expanded);
    }

    for enumeration in &sorted_enums {
        let Token::Enum(e) = &*enumeration.borrow() else {
            // TODO: log
            continue;
        };

        let mut expanded = e.expand(&ctx);
        tokens.append(&mut expanded);
    }

    let expanded = quote! {
        #(#tokens)*
    };

    expanded
}
