use cainome_parser::{AbiParser, ParserContext};

use cainome_rs::expand::{ExpansionContext, ExpansionContextFactory};
use starknet::core::types::contract::legacy::{LegacyContractClass, RawLegacyAbiEntry};
use starknet::core::types::contract::{AbiEntry, SierraClass};
use std::collections::HashMap;
use std::fs::{self, File};

fn read_file_legacy(file_path: &str) -> Vec<RawLegacyAbiEntry> {
    println!("cargo:trace=Reading ABI from file: {file_path}");
    let file = File::open(file_path).unwrap();

    if let Ok(class) = serde_json::from_reader::<_, LegacyContractClass>(file) {
        return class.abi;
    }

    let file = File::open(file_path).unwrap();

    if let Ok(abi) = serde_json::from_reader::<_, Vec<RawLegacyAbiEntry>>(file) {
        return abi;
    }

    panic!("Failed to parse legacy ABI file");
}

fn legacy_expand(out_name: &str, ctx: &ExpansionContext) {
    let cwd = std::env::current_dir().unwrap();
    println!("cargo:trace=Current working directory: {cwd:?}");

    let abi = read_file_legacy(ctx.contract_source.as_ref());

    let registry =
        AbiParser::build_registry(abi, ParserContext::from(ctx)).expect("failed tokens parsing");

    let expanded = cainome_rs::abi_to_tokenstream(&registry, &ctx).expect("expansion failed");

    let debug_data = expanded.to_string();

    let syntax_tree = syn::parse2::<syn::File>(expanded)
        .inspect_err(|err| {
            println!("cargo:trace=Error expanding {err} code to: \n\n{debug_data}\n\n");
        })
        .unwrap();
    let s = prettyplease::unparse(&syntax_tree);

    let content = format!(
        "// ****\n// Auto-generated by cainome do not edit.\n// ****\n\n#![allow(clippy::all)]\n#![allow(warnings)]\n\n{s}"
    );

    let path = cwd.to_str().unwrap();
    fs::write(format!("{path}/{out_name}"), content).unwrap()
}

fn read_file(file_path: &str) -> Vec<AbiEntry> {
    println!("cargo:trace=Reading ABI from file: {file_path}");
    let file = File::open(file_path).unwrap_or_else(|_| panic!("{file_path} not found"));

    if let Ok(class) = serde_json::from_reader::<_, SierraClass>(file) {
        return class.abi;
    }

    let file = File::open(file_path).unwrap();

    if let Ok(abi) = serde_json::from_reader::<_, Vec<AbiEntry>>(file) {
        return abi;
    }

    panic!("Failed to parse legacy ABI file");
}

fn expand(out_name: &str, ctx: &ExpansionContext) {
    let cwd = std::env::current_dir().unwrap();
    println!("cargo:debug=Current working directory: {cwd:?}");
    let path = cwd.to_str().unwrap();

    let abi = read_file(ctx.contract_source.as_ref());

    let registry =
        AbiParser::build_registry(abi, ParserContext::from(ctx)).expect("failed tokens parsing");

    let expanded = cainome_rs::abi_to_tokenstream(&registry, ctx).expect("expansion failed");

    let syntax_tree = syn::parse2::<syn::File>(expanded).unwrap();
    let s = prettyplease::unparse(&syntax_tree);

    let content = format!(
        "// ****\n// Auto-generated by cainome do not edit.\n// ****\n\n#![allow(clippy::all)]\n#![allow(warnings)]\n\n{s}",
    );

    println!("cargo:trace=Writing expanded code to: {path}/{out_name}");

    fs::write(format!("{path}/{out_name}"), content).unwrap()
}

fn main() {
    // return;

    legacy_expand(
        "./src/bindings/kkrt_account_cairo0.rs",
        &ExpansionContextFactory::new("../../contracts/cairo0/kkrt_account_cairo0.json")
            .with_contract_name("MyContract")
            .with_derives(["Debug"])
            .with_cainome_serde_path("cainome_cairo_serde")
            // .with_add_deployment(false)
            .build(),
    );
    expand(
        "./src/bindings/structs.rs",
        &ExpansionContextFactory::new("../../contracts/abi/gen.abi.json")
            .with_contract_name("Structs")
            .with_cainome_serde_path("cainome_cairo_serde")
            .with_root_module_path("crate::bindings::structs")
            .with_derives([
                "Debug",
                "Clone",
                "PartialEq",
                "serde::Serialize",
                "serde::Deserialize",
            ])
            // .with_aliases(HashMap::from([
            //     (
            //         "contracts::gen::gen::MyStruct::<core::felt252>".to_string(),
            //         "contracts::gen::gen::MyStructFelt".to_string(),
            //     ),
            //     (
            //         "contracts::gen::gen::MyStruct::<core::integer::u256>".to_string(),
            //         "contracts::gen::gen::MyStructFeltU256".to_string(),
            //     ),
            // ]))
            .build(),
    );
    expand(
        "./src/bindings/components_events_flat.rs",
        &ExpansionContextFactory::new("../../contracts/abi/components.abi.json")
            .with_contract_name("ComponentsEventsFlat")
            .with_cainome_serde_path("cainome_cairo_serde")
            .with_root_module_path("crate::bindings::components_events_flat")
            .with_aliases(HashMap::from([
                (
                    "contracts::abicov::components::simple_component::Event".to_string(),
                    "SimpleEvent".to_string(),
                ),
                (
                    "contracts::abicov::components::simple_component::Written".to_string(),
                    "SimpleWritten".to_string(),
                ),
                (
                    "contracts::abicov::components::simple_component::MyStruct".to_string(),
                    "MyStructSimple".to_string(),
                ),
                (
                    "contracts::abicov::components::simple_component_other::Event".to_string(),
                    "OtherEvent".to_string(),
                ),
                (
                    "contracts::abicov::components::simple_component_other::Written".to_string(),
                    "OtherWritten".to_string(),
                ),
                (
                    "contracts::abicov::components::simple_component_other::MyStruct".to_string(),
                    "MyStructOther".to_string(),
                ),
                (
                    "contracts::abicov::components::components_contract::OutterEvent".to_string(),
                    "OutterEvent".to_string(),
                ),
            ]))
            .build(),
    );
    expand(
        "./src/bindings/simple_get_set.rs",
        &ExpansionContextFactory::new("../../contracts/abi/simple_get_set.abi.json")
            .with_contract_name("SimpleGetSet")
            .with_cainome_serde_path("cainome_cairo_serde")
            .with_root_module_path("crate::bindings::simple_get_set")
            .build(),
    );
    expand(
        "./src/bindings/erc20.rs",
        &ExpansionContextFactory::new("../../contracts/prebuilt/erc20.json")
            .with_contract_name("ERC20")
            .with_cainome_serde_path("cainome_cairo_serde")
            .with_root_module_path("crate::bindings::erc20")
            .build(),
    );
    expand(
        "./src/bindings/components_events.rs",
        &ExpansionContextFactory::new("../../contracts/abi/components.abi.json")
            .with_contract_name("ComponentsEvents")
            .with_cainome_serde_path("cainome_cairo_serde")
            .with_root_module_path("crate::bindings::components_events")
            .build(),
    );
    legacy_expand(
        "./src/bindings/udc.rs",
        &ExpansionContextFactory::new("../../contracts/prebuilt/udc.json")
            .with_contract_name("UDC")
            .with_derives(["Debug"])
            .with_cainome_serde_path("cainome_cairo_serde")
            .with_is_legacy(true)
            .with_add_declaration(true)
            .with_add_deployment(false)
            .build(),
    );
    expand(
        "./src/bindings/substitutions.rs",
        &ExpansionContextFactory::new("../../contracts/abi/structs.abi.json")
            .with_contract_name("Substitutions")
            .with_cainome_serde_path("cainome_cairo_serde")
            .with_root_module_path("crate::bindings::substitutions")
            .with_derives(["serde::Serialize", "serde::Deserialize"])
            .with_substitutions(HashMap::from([
                (
                    "contracts::abicov::structs::GenericOne::<core::felt252>".to_string(),
                    "crate::test_substitutions::GenericOneFelt".to_string(),
                ),
                // (
                //     "contracts::abicov::structs::GenericOne::<core::felt252>".to_string(),
                //     "crate::test_substitutions::GenericOne::<starknet::core::types::Felt>"
                //         .to_string(),
                // ),
                (
                    "contracts::abicov::structs::GenericOne::<core::integer::u256>".to_string(),
                    "crate::test_substitutions::GenericOneu256".to_string(),
                ),
                (
                    "contracts::abicov::structs::GenericOne::<core::integer::u64>".to_string(),
                    "crate::test_substitutions::GenericOneu64".to_string(),
                ),
                (
                    "contracts::abicov::structs::GenericOne::<core::array::Span::<core::felt252>>"
                        .to_string(),
                    "crate::test_substitutions::GenericOneSpanFelt".to_string(),
                ),
            ]))
            .build(),
    );
}
