[package]
name = "integration-tests"
version = "0.0.1"
edition = "2021"
authors = ["baitcode <batiyiv@gmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/cartridge-gg/cainome"
homepage = "https://github.com/cartridge-gg/cainome"
description = """
Integration tests for cainome
"""
keywords = ["cairo", "starknet", "web3"]
exclude = [".github/**", "images/**"]

[build-dependencies]
cainome-parser.workspace = true
cainome-rs.workspace = true
starknet.workspace = true
serde_json.workspace = true
syn = { version = "2.0", features = [ "extra-traits" ]}
prettyplease = "0.2.19"

[dev-dependencies]
tracing.workspace = true
starknet.workspace = true
cainome-cairo-serde.workspace = true
cainome-parser.workspace = true
cainome-rs.workspace = true
thiserror.workspace = true
tokio.workspace = true
katana-runner.workspace = true
starknet-types-core.workspace = true
cairo-lang-starknet-classes.workspace = true
serde.workspace = true
serde_json.workspace = true
cainome-rs-macro = { path = "../rs-macro" }
cainome-cairo-serde-derive = { path = "../cairo-serde-derive" }
smol_str = "=0.3.2"
rand = "0.9.2"
paste = "1.0"
starknet_api = "=0.16.0-rc.1"