// ****
// Auto-generated by cainome do not edit.
// ****

#![allow(clippy::all)]
#![allow(warnings)]

pub mod openzeppelin {
    pub mod access {
        pub mod ownable {
            pub mod ownable {
                pub mod OwnableComponent {
                    pub enum Event {
                        OwnershipTransferred(
                            crate::bindings::erc20::openzeppelin::access::ownable::ownable::OwnableComponent::OwnershipTransferred,
                        ),
                    }
                    impl cainome_cairo_serde::CairoSerde for Event {
                        type RustType = Self;
                        const SERIALIZED_SIZE: std::option::Option<usize> =
                            std::option::Option::None;
                        #[inline]
                        fn cairo_serialized_size(__rust: &Self::RustType) -> usize {
                            match __rust {
                                Event::OwnershipTransferred(val) => {
                                    crate::bindings::erc20::openzeppelin::access::ownable::ownable::OwnableComponent::OwnershipTransferred::cairo_serialized_size(
                                        val,
                                    ) + 1
                                }
                                _ => 0,
                            }
                        }
                        fn cairo_serialize(
                            __rust: &Self::RustType,
                        ) -> Vec<starknet::core::types::Felt> {
                            match __rust {
                                Event::OwnershipTransferred(val) => {
                                    let mut temp = vec![];
                                    temp.extend(usize::cairo_serialize(&0usize));
                                    temp.extend(
                                        crate::bindings::erc20::openzeppelin::access::ownable::ownable::OwnableComponent::OwnershipTransferred::cairo_serialize(
                                            val,
                                        ),
                                    );
                                    temp
                                }
                                _ => vec![],
                            }
                        }
                        fn cairo_deserialize(
                            __felts: &[starknet::core::types::Felt],
                            __offset: usize,
                        ) -> cainome_cairo_serde::Result<Self::RustType> {
                            let __f = __felts[__offset];
                            let __index =
                                u128::from_be_bytes(__f.to_bytes_be()[16..].try_into().unwrap());
                            match __index as usize {
                                0usize => {
                                    Ok(
                                        Event::OwnershipTransferred(
                                            crate::bindings::erc20::openzeppelin::access::ownable::ownable::OwnableComponent::OwnershipTransferred::cairo_deserialize(
                                                __felts,
                                                __offset + 1,
                                            )?,
                                        ),
                                    )
                                }
                                _ => {
                                    return Err(
                                        cainome_cairo_serde::Error::Deserialize(
                                            format!("Index not handle for enum {}", "Event"),
                                        ),
                                    );
                                }
                            }
                        }
                    }
                    impl Event {
                        pub fn event_selector() -> starknet::core::types::Felt {
                            starknet::core::utils::get_selector_from_name("Event").unwrap()
                        }
                        pub fn event_name() -> &'static str {
                            "Event"
                        }
                        pub(crate) fn try_from_event(
                            from_address: starknet::core::types::Felt,
                            keys: Vec<starknet::core::types::Felt>,
                            data: Vec<starknet::core::types::Felt>,
                        ) -> Result<Self, String> {
                            if keys.is_empty() {
                                return Err("Event has no key".to_string());
                            }
                            use cainome_cairo_serde::CairoSerde;
                            if keys[0]
                                == starknet::core::utils::get_selector_from_name(
                                    "OwnershipTransferred",
                                )
                                .unwrap_or_else(|_| {
                                    panic!("Invalid selector for {}", "OwnershipTransferred")
                                })
                            {
                                let res = crate::bindings::erc20::openzeppelin::access::ownable::ownable::OwnableComponent::OwnershipTransferred::cairo_deserialize(
                                        &data,
                                        0,
                                    )
                                    .map_err(|e| {
                                        format!(
                                            "Could not deserialize {} event data: {:?}",
                                            "crate::bindings::erc20::openzeppelin::access::ownable::ownable::OwnableComponent::OwnershipTransferred",
                                            e
                                        )
                                    })?;
                                return Ok(Event::OwnershipTransferred(res));
                            }
                            Err(format!("Could not match any event from keys {:?}", keys))
                        }
                    }
                    impl TryFrom<starknet::core::types::EmittedEvent> for Event {
                        type Error = String;
                        fn try_from(
                            event: starknet::core::types::EmittedEvent,
                        ) -> Result<Self, Self::Error> {
                            Self::try_from_event(event.from_address, event.keys, event.data)
                        }
                    }
                    impl TryFrom<starknet::core::types::Event> for Event {
                        type Error = String;
                        fn try_from(
                            event: starknet::core::types::Event,
                        ) -> Result<Self, Self::Error> {
                            Self::try_from_event(event.from_address, event.keys, event.data)
                        }
                    }
                    pub struct OwnershipTransferred {
                        pub previous_owner: cainome_cairo_serde::ContractAddress,
                        pub new_owner: cainome_cairo_serde::ContractAddress,
                    }
                    impl cainome_cairo_serde::CairoSerde for OwnershipTransferred {
                        type RustType = Self;
                        const SERIALIZED_SIZE: std::option::Option<usize> = None;
                        #[inline]
                        fn cairo_serialized_size(__rust: &Self::RustType) -> usize {
                            let mut __size = 0;
                            __size += cainome_cairo_serde::ContractAddress::cairo_serialized_size(
                                &__rust.previous_owner,
                            );
                            __size += cainome_cairo_serde::ContractAddress::cairo_serialized_size(
                                &__rust.new_owner,
                            );
                            __size
                        }
                        fn cairo_serialize(
                            __rust: &Self::RustType,
                        ) -> Vec<starknet::core::types::Felt> {
                            let mut __out: Vec<starknet::core::types::Felt> = vec![];
                            __out.extend(cainome_cairo_serde::ContractAddress::cairo_serialize(
                                &__rust.previous_owner,
                            ));
                            __out.extend(cainome_cairo_serde::ContractAddress::cairo_serialize(
                                &__rust.new_owner,
                            ));
                            __out
                        }
                        fn cairo_deserialize(
                            __felts: &[starknet::core::types::Felt],
                            __offset: usize,
                        ) -> cainome_cairo_serde::Result<Self::RustType> {
                            let mut __offset = __offset;
                            let previous_owner =
                                cainome_cairo_serde::ContractAddress::cairo_deserialize(
                                    __felts, __offset,
                                )?;
                            __offset += cainome_cairo_serde::ContractAddress::cairo_serialized_size(
                                &previous_owner,
                            );
                            let new_owner =
                                cainome_cairo_serde::ContractAddress::cairo_deserialize(
                                    __felts, __offset,
                                )?;
                            __offset += cainome_cairo_serde::ContractAddress::cairo_serialized_size(
                                &new_owner,
                            );
                            Ok(OwnershipTransferred {
                                previous_owner,
                                new_owner,
                            })
                        }
                    }
                    impl OwnershipTransferred {
                        pub fn event_selector() -> starknet::core::types::Felt {
                            starknet::core::utils::get_selector_from_name("OwnershipTransferred")
                                .unwrap()
                        }
                        pub fn event_name() -> &'static str {
                            "OwnershipTransferred"
                        }
                        pub(crate) fn try_from_event(
                            from_address: starknet::core::types::Felt,
                            keys: Vec<starknet::core::types::Felt>,
                            data: Vec<starknet::core::types::Felt>,
                        ) -> Result<Self, String> {
                            if keys.is_empty() {
                                return Err("Event has no key".to_string());
                            }
                            use cainome_cairo_serde::CairoSerde;
                            if keys[0]
                                == starknet::core::utils::get_selector_from_name(
                                    "OwnershipTransferred",
                                )
                                .unwrap_or_else(|_| {
                                    panic!("Invalid selector for {}", "OwnershipTransferred")
                                })
                            {
                                let res = OwnershipTransferred::cairo_deserialize(&data, 0)
                                    .map_err(|e| {
                                        format!(
                                            "Could not deserialize {} event data: {:?}",
                                            "OwnershipTransferred", e
                                        )
                                    })?;
                                return Ok(res);
                            }
                            Err(format!("Could not match any event from keys {:?}", keys))
                        }
                    }
                    impl TryFrom<starknet::core::types::EmittedEvent> for OwnershipTransferred {
                        type Error = String;
                        fn try_from(
                            event: starknet::core::types::EmittedEvent,
                        ) -> Result<Self, Self::Error> {
                            Self::try_from_event(event.from_address, event.keys, event.data)
                        }
                    }
                    impl TryFrom<starknet::core::types::Event> for OwnershipTransferred {
                        type Error = String;
                        fn try_from(
                            event: starknet::core::types::Event,
                        ) -> Result<Self, Self::Error> {
                            Self::try_from_event(event.from_address, event.keys, event.data)
                        }
                    }
                }
            }
        }
    }
    pub mod presets {
        pub mod erc20 {
            pub mod ERC20 {
                pub enum Event {
                    ERC20Event(
                        crate::bindings::erc20::openzeppelin::token::erc20::erc20::ERC20Component::Event,
                    ),
                    OwnableEvent(
                        crate::bindings::erc20::openzeppelin::access::ownable::ownable::OwnableComponent::Event,
                    ),
                }
                impl cainome_cairo_serde::CairoSerde for Event {
                    type RustType = Self;
                    const SERIALIZED_SIZE: std::option::Option<usize> = std::option::Option::None;
                    #[inline]
                    fn cairo_serialized_size(__rust: &Self::RustType) -> usize {
                        match __rust {
                            Event::ERC20Event(val) => {
                                crate::bindings::erc20::openzeppelin::token::erc20::erc20::ERC20Component::Event::cairo_serialized_size(
                                    val,
                                ) + 1
                            }
                            Event::OwnableEvent(val) => {
                                crate::bindings::erc20::openzeppelin::access::ownable::ownable::OwnableComponent::Event::cairo_serialized_size(
                                    val,
                                ) + 1
                            }
                            _ => 0,
                        }
                    }
                    fn cairo_serialize(
                        __rust: &Self::RustType,
                    ) -> Vec<starknet::core::types::Felt> {
                        match __rust {
                            Event::ERC20Event(val) => {
                                let mut temp = vec![];
                                temp.extend(usize::cairo_serialize(&0usize));
                                temp.extend(
                                    crate::bindings::erc20::openzeppelin::token::erc20::erc20::ERC20Component::Event::cairo_serialize(
                                        val,
                                    ),
                                );
                                temp
                            }
                            Event::OwnableEvent(val) => {
                                let mut temp = vec![];
                                temp.extend(usize::cairo_serialize(&1usize));
                                temp.extend(
                                    crate::bindings::erc20::openzeppelin::access::ownable::ownable::OwnableComponent::Event::cairo_serialize(
                                        val,
                                    ),
                                );
                                temp
                            }
                            _ => vec![],
                        }
                    }
                    fn cairo_deserialize(
                        __felts: &[starknet::core::types::Felt],
                        __offset: usize,
                    ) -> cainome_cairo_serde::Result<Self::RustType> {
                        let __f = __felts[__offset];
                        let __index =
                            u128::from_be_bytes(__f.to_bytes_be()[16..].try_into().unwrap());
                        match __index as usize {
                            0usize => {
                                Ok(
                                    Event::ERC20Event(
                                        crate::bindings::erc20::openzeppelin::token::erc20::erc20::ERC20Component::Event::cairo_deserialize(
                                            __felts,
                                            __offset + 1,
                                        )?,
                                    ),
                                )
                            }
                            1usize => {
                                Ok(
                                    Event::OwnableEvent(
                                        crate::bindings::erc20::openzeppelin::access::ownable::ownable::OwnableComponent::Event::cairo_deserialize(
                                            __felts,
                                            __offset + 1,
                                        )?,
                                    ),
                                )
                            }
                            _ => {
                                return Err(
                                    cainome_cairo_serde::Error::Deserialize(
                                        format!("Index not handle for enum {}", "Event"),
                                    ),
                                );
                            }
                        }
                    }
                }
                impl Event {
                    pub fn event_selector() -> starknet::core::types::Felt {
                        starknet::core::utils::get_selector_from_name("Event").unwrap()
                    }
                    pub fn event_name() -> &'static str {
                        "Event"
                    }
                    pub(crate) fn try_from_event(
                        from_address: starknet::core::types::Felt,
                        keys: Vec<starknet::core::types::Felt>,
                        data: Vec<starknet::core::types::Felt>,
                    ) -> Result<Self, String> {
                        if keys.is_empty() {
                            return Err("Event has no key".to_string());
                        }
                        use cainome_cairo_serde::CairoSerde;
                        if keys[0]
                            == starknet::core::utils::get_selector_from_name("ERC20Event")
                                .unwrap_or_else(|_| panic!("Invalid selector for {}", "ERC20Event"))
                        {
                            let res = crate::bindings::erc20::openzeppelin::token::erc20::erc20::ERC20Component::Event::try_from_event(
                                from_address,
                                keys.to_vec(),
                                data,
                            )?;
                            return Ok(Event::ERC20Event(res));
                        }
                        if keys[0]
                            == starknet::core::utils::get_selector_from_name("OwnableEvent")
                                .unwrap_or_else(|_| {
                                    panic!("Invalid selector for {}", "OwnableEvent")
                                })
                        {
                            let res = crate::bindings::erc20::openzeppelin::access::ownable::ownable::OwnableComponent::Event::try_from_event(
                                from_address,
                                keys.to_vec(),
                                data,
                            )?;
                            return Ok(Event::OwnableEvent(res));
                        }
                        Err(format!("Could not match any event from keys {:?}", keys))
                    }
                }
                impl TryFrom<starknet::core::types::EmittedEvent> for Event {
                    type Error = String;
                    fn try_from(
                        event: starknet::core::types::EmittedEvent,
                    ) -> Result<Self, Self::Error> {
                        Self::try_from_event(event.from_address, event.keys, event.data)
                    }
                }
                impl TryFrom<starknet::core::types::Event> for Event {
                    type Error = String;
                    fn try_from(event: starknet::core::types::Event) -> Result<Self, Self::Error> {
                        Self::try_from_event(event.from_address, event.keys, event.data)
                    }
                }
            }
        }
    }
    pub mod token {
        pub mod erc20 {
            pub mod erc20 {
                pub mod ERC20Component {
                    pub struct Approval {
                        pub owner: cainome_cairo_serde::ContractAddress,
                        pub spender: cainome_cairo_serde::ContractAddress,
                        pub value: cainome_cairo_serde::U256,
                    }
                    impl cainome_cairo_serde::CairoSerde for Approval {
                        type RustType = Self;
                        const SERIALIZED_SIZE: std::option::Option<usize> = None;
                        #[inline]
                        fn cairo_serialized_size(__rust: &Self::RustType) -> usize {
                            let mut __size = 0;
                            __size += cainome_cairo_serde::ContractAddress::cairo_serialized_size(
                                &__rust.owner,
                            );
                            __size += cainome_cairo_serde::ContractAddress::cairo_serialized_size(
                                &__rust.spender,
                            );
                            __size +=
                                cainome_cairo_serde::U256::cairo_serialized_size(&__rust.value);
                            __size
                        }
                        fn cairo_serialize(
                            __rust: &Self::RustType,
                        ) -> Vec<starknet::core::types::Felt> {
                            let mut __out: Vec<starknet::core::types::Felt> = vec![];
                            __out.extend(cainome_cairo_serde::ContractAddress::cairo_serialize(
                                &__rust.owner,
                            ));
                            __out.extend(cainome_cairo_serde::ContractAddress::cairo_serialize(
                                &__rust.spender,
                            ));
                            __out.extend(cainome_cairo_serde::U256::cairo_serialize(&__rust.value));
                            __out
                        }
                        fn cairo_deserialize(
                            __felts: &[starknet::core::types::Felt],
                            __offset: usize,
                        ) -> cainome_cairo_serde::Result<Self::RustType> {
                            let mut __offset = __offset;
                            let owner = cainome_cairo_serde::ContractAddress::cairo_deserialize(
                                __felts, __offset,
                            )?;
                            __offset +=
                                cainome_cairo_serde::ContractAddress::cairo_serialized_size(&owner);
                            let spender = cainome_cairo_serde::ContractAddress::cairo_deserialize(
                                __felts, __offset,
                            )?;
                            __offset += cainome_cairo_serde::ContractAddress::cairo_serialized_size(
                                &spender,
                            );
                            let value =
                                cainome_cairo_serde::U256::cairo_deserialize(__felts, __offset)?;
                            __offset += cainome_cairo_serde::U256::cairo_serialized_size(&value);
                            Ok(Approval {
                                owner,
                                spender,
                                value,
                            })
                        }
                    }
                    impl Approval {
                        pub fn event_selector() -> starknet::core::types::Felt {
                            starknet::core::utils::get_selector_from_name("Approval").unwrap()
                        }
                        pub fn event_name() -> &'static str {
                            "Approval"
                        }
                        pub(crate) fn try_from_event(
                            from_address: starknet::core::types::Felt,
                            keys: Vec<starknet::core::types::Felt>,
                            data: Vec<starknet::core::types::Felt>,
                        ) -> Result<Self, String> {
                            if keys.is_empty() {
                                return Err("Event has no key".to_string());
                            }
                            use cainome_cairo_serde::CairoSerde;
                            if keys[0]
                                == starknet::core::utils::get_selector_from_name("Approval")
                                    .unwrap_or_else(|_| {
                                        panic!("Invalid selector for {}", "Approval")
                                    })
                            {
                                let res = Approval::cairo_deserialize(&data, 0).map_err(|e| {
                                    format!(
                                        "Could not deserialize {} event data: {:?}",
                                        "Approval", e
                                    )
                                })?;
                                return Ok(res);
                            }
                            Err(format!("Could not match any event from keys {:?}", keys))
                        }
                    }
                    impl TryFrom<starknet::core::types::EmittedEvent> for Approval {
                        type Error = String;
                        fn try_from(
                            event: starknet::core::types::EmittedEvent,
                        ) -> Result<Self, Self::Error> {
                            Self::try_from_event(event.from_address, event.keys, event.data)
                        }
                    }
                    impl TryFrom<starknet::core::types::Event> for Approval {
                        type Error = String;
                        fn try_from(
                            event: starknet::core::types::Event,
                        ) -> Result<Self, Self::Error> {
                            Self::try_from_event(event.from_address, event.keys, event.data)
                        }
                    }
                    pub struct Transfer {
                        pub from: cainome_cairo_serde::ContractAddress,
                        pub to: cainome_cairo_serde::ContractAddress,
                        pub value: cainome_cairo_serde::U256,
                    }
                    impl cainome_cairo_serde::CairoSerde for Transfer {
                        type RustType = Self;
                        const SERIALIZED_SIZE: std::option::Option<usize> = None;
                        #[inline]
                        fn cairo_serialized_size(__rust: &Self::RustType) -> usize {
                            let mut __size = 0;
                            __size += cainome_cairo_serde::ContractAddress::cairo_serialized_size(
                                &__rust.from,
                            );
                            __size += cainome_cairo_serde::ContractAddress::cairo_serialized_size(
                                &__rust.to,
                            );
                            __size +=
                                cainome_cairo_serde::U256::cairo_serialized_size(&__rust.value);
                            __size
                        }
                        fn cairo_serialize(
                            __rust: &Self::RustType,
                        ) -> Vec<starknet::core::types::Felt> {
                            let mut __out: Vec<starknet::core::types::Felt> = vec![];
                            __out.extend(cainome_cairo_serde::ContractAddress::cairo_serialize(
                                &__rust.from,
                            ));
                            __out.extend(cainome_cairo_serde::ContractAddress::cairo_serialize(
                                &__rust.to,
                            ));
                            __out.extend(cainome_cairo_serde::U256::cairo_serialize(&__rust.value));
                            __out
                        }
                        fn cairo_deserialize(
                            __felts: &[starknet::core::types::Felt],
                            __offset: usize,
                        ) -> cainome_cairo_serde::Result<Self::RustType> {
                            let mut __offset = __offset;
                            let from = cainome_cairo_serde::ContractAddress::cairo_deserialize(
                                __felts, __offset,
                            )?;
                            __offset +=
                                cainome_cairo_serde::ContractAddress::cairo_serialized_size(&from);
                            let to = cainome_cairo_serde::ContractAddress::cairo_deserialize(
                                __felts, __offset,
                            )?;
                            __offset +=
                                cainome_cairo_serde::ContractAddress::cairo_serialized_size(&to);
                            let value =
                                cainome_cairo_serde::U256::cairo_deserialize(__felts, __offset)?;
                            __offset += cainome_cairo_serde::U256::cairo_serialized_size(&value);
                            Ok(Transfer { from, to, value })
                        }
                    }
                    impl Transfer {
                        pub fn event_selector() -> starknet::core::types::Felt {
                            starknet::core::utils::get_selector_from_name("Transfer").unwrap()
                        }
                        pub fn event_name() -> &'static str {
                            "Transfer"
                        }
                        pub(crate) fn try_from_event(
                            from_address: starknet::core::types::Felt,
                            keys: Vec<starknet::core::types::Felt>,
                            data: Vec<starknet::core::types::Felt>,
                        ) -> Result<Self, String> {
                            if keys.is_empty() {
                                return Err("Event has no key".to_string());
                            }
                            use cainome_cairo_serde::CairoSerde;
                            if keys[0]
                                == starknet::core::utils::get_selector_from_name("Transfer")
                                    .unwrap_or_else(|_| {
                                        panic!("Invalid selector for {}", "Transfer")
                                    })
                            {
                                let res = Transfer::cairo_deserialize(&data, 0).map_err(|e| {
                                    format!(
                                        "Could not deserialize {} event data: {:?}",
                                        "Transfer", e
                                    )
                                })?;
                                return Ok(res);
                            }
                            Err(format!("Could not match any event from keys {:?}", keys))
                        }
                    }
                    impl TryFrom<starknet::core::types::EmittedEvent> for Transfer {
                        type Error = String;
                        fn try_from(
                            event: starknet::core::types::EmittedEvent,
                        ) -> Result<Self, Self::Error> {
                            Self::try_from_event(event.from_address, event.keys, event.data)
                        }
                    }
                    impl TryFrom<starknet::core::types::Event> for Transfer {
                        type Error = String;
                        fn try_from(
                            event: starknet::core::types::Event,
                        ) -> Result<Self, Self::Error> {
                            Self::try_from_event(event.from_address, event.keys, event.data)
                        }
                    }
                    pub enum Event {
                        Transfer(
                            crate::bindings::erc20::openzeppelin::token::erc20::erc20::ERC20Component::Transfer,
                        ),
                        Approval(
                            crate::bindings::erc20::openzeppelin::token::erc20::erc20::ERC20Component::Approval,
                        ),
                    }
                    impl cainome_cairo_serde::CairoSerde for Event {
                        type RustType = Self;
                        const SERIALIZED_SIZE: std::option::Option<usize> =
                            std::option::Option::None;
                        #[inline]
                        fn cairo_serialized_size(__rust: &Self::RustType) -> usize {
                            match __rust {
                                Event::Transfer(val) => {
                                    crate::bindings::erc20::openzeppelin::token::erc20::erc20::ERC20Component::Transfer::cairo_serialized_size(
                                        val,
                                    ) + 1
                                }
                                Event::Approval(val) => {
                                    crate::bindings::erc20::openzeppelin::token::erc20::erc20::ERC20Component::Approval::cairo_serialized_size(
                                        val,
                                    ) + 1
                                }
                                _ => 0,
                            }
                        }
                        fn cairo_serialize(
                            __rust: &Self::RustType,
                        ) -> Vec<starknet::core::types::Felt> {
                            match __rust {
                                Event::Transfer(val) => {
                                    let mut temp = vec![];
                                    temp.extend(usize::cairo_serialize(&0usize));
                                    temp.extend(
                                        crate::bindings::erc20::openzeppelin::token::erc20::erc20::ERC20Component::Transfer::cairo_serialize(
                                            val,
                                        ),
                                    );
                                    temp
                                }
                                Event::Approval(val) => {
                                    let mut temp = vec![];
                                    temp.extend(usize::cairo_serialize(&1usize));
                                    temp.extend(
                                        crate::bindings::erc20::openzeppelin::token::erc20::erc20::ERC20Component::Approval::cairo_serialize(
                                            val,
                                        ),
                                    );
                                    temp
                                }
                                _ => vec![],
                            }
                        }
                        fn cairo_deserialize(
                            __felts: &[starknet::core::types::Felt],
                            __offset: usize,
                        ) -> cainome_cairo_serde::Result<Self::RustType> {
                            let __f = __felts[__offset];
                            let __index =
                                u128::from_be_bytes(__f.to_bytes_be()[16..].try_into().unwrap());
                            match __index as usize {
                                0usize => {
                                    Ok(
                                        Event::Transfer(
                                            crate::bindings::erc20::openzeppelin::token::erc20::erc20::ERC20Component::Transfer::cairo_deserialize(
                                                __felts,
                                                __offset + 1,
                                            )?,
                                        ),
                                    )
                                }
                                1usize => {
                                    Ok(
                                        Event::Approval(
                                            crate::bindings::erc20::openzeppelin::token::erc20::erc20::ERC20Component::Approval::cairo_deserialize(
                                                __felts,
                                                __offset + 1,
                                            )?,
                                        ),
                                    )
                                }
                                _ => {
                                    return Err(
                                        cainome_cairo_serde::Error::Deserialize(
                                            format!("Index not handle for enum {}", "Event"),
                                        ),
                                    );
                                }
                            }
                        }
                    }
                    impl Event {
                        pub fn event_selector() -> starknet::core::types::Felt {
                            starknet::core::utils::get_selector_from_name("Event").unwrap()
                        }
                        pub fn event_name() -> &'static str {
                            "Event"
                        }
                        pub(crate) fn try_from_event(
                            from_address: starknet::core::types::Felt,
                            keys: Vec<starknet::core::types::Felt>,
                            data: Vec<starknet::core::types::Felt>,
                        ) -> Result<Self, String> {
                            if keys.is_empty() {
                                return Err("Event has no key".to_string());
                            }
                            use cainome_cairo_serde::CairoSerde;
                            if keys[0]
                                == starknet::core::utils::get_selector_from_name("Transfer")
                                    .unwrap_or_else(|_| {
                                        panic!("Invalid selector for {}", "Transfer")
                                    })
                            {
                                let res = crate::bindings::erc20::openzeppelin::token::erc20::erc20::ERC20Component::Transfer::cairo_deserialize(
                                        &data,
                                        0,
                                    )
                                    .map_err(|e| {
                                        format!(
                                            "Could not deserialize {} event data: {:?}",
                                            "crate::bindings::erc20::openzeppelin::token::erc20::erc20::ERC20Component::Transfer",
                                            e
                                        )
                                    })?;
                                return Ok(Event::Transfer(res));
                            }
                            if keys[0]
                                == starknet::core::utils::get_selector_from_name("Approval")
                                    .unwrap_or_else(|_| {
                                        panic!("Invalid selector for {}", "Approval")
                                    })
                            {
                                let res = crate::bindings::erc20::openzeppelin::token::erc20::erc20::ERC20Component::Approval::cairo_deserialize(
                                        &data,
                                        0,
                                    )
                                    .map_err(|e| {
                                        format!(
                                            "Could not deserialize {} event data: {:?}",
                                            "crate::bindings::erc20::openzeppelin::token::erc20::erc20::ERC20Component::Approval",
                                            e
                                        )
                                    })?;
                                return Ok(Event::Approval(res));
                            }
                            Err(format!("Could not match any event from keys {:?}", keys))
                        }
                    }
                    impl TryFrom<starknet::core::types::EmittedEvent> for Event {
                        type Error = String;
                        fn try_from(
                            event: starknet::core::types::EmittedEvent,
                        ) -> Result<Self, Self::Error> {
                            Self::try_from_event(event.from_address, event.keys, event.data)
                        }
                    }
                    impl TryFrom<starknet::core::types::Event> for Event {
                        type Error = String;
                        fn try_from(
                            event: starknet::core::types::Event,
                        ) -> Result<Self, Self::Error> {
                            Self::try_from_event(event.from_address, event.keys, event.data)
                        }
                    }
                }
            }
        }
    }
}
pub struct ERC20Calldata {
    pub owner: cainome_cairo_serde::ContractAddress,
}
impl cainome_cairo_serde::CairoSerde for ERC20Calldata {
    type RustType = Self;
    const SERIALIZED_SIZE: std::option::Option<usize> = None;
    #[inline]
    fn cairo_serialized_size(__rust: &Self::RustType) -> usize {
        let mut __size = 0;
        __size += cainome_cairo_serde::ContractAddress::cairo_serialized_size(&__rust.owner);
        __size
    }
    fn cairo_serialize(__rust: &Self::RustType) -> Vec<starknet::core::types::Felt> {
        let mut __out: Vec<starknet::core::types::Felt> = vec![];
        __out.extend(cainome_cairo_serde::ContractAddress::cairo_serialize(
            &__rust.owner,
        ));
        __out
    }
    fn cairo_deserialize(
        __felts: &[starknet::core::types::Felt],
        __offset: usize,
    ) -> cainome_cairo_serde::Result<Self::RustType> {
        let mut __offset = __offset;
        let owner = cainome_cairo_serde::ContractAddress::cairo_deserialize(__felts, __offset)?;
        __offset += cainome_cairo_serde::ContractAddress::cairo_serialized_size(&owner);
        Ok(ERC20Calldata { owner })
    }
}
pub struct ERC20<A: starknet::accounts::ConnectedAccount + Sync> {
    pub address: starknet::core::types::Felt,
    pub account: A,
    pub block_id: starknet::core::types::BlockId,
}
impl<A: starknet::accounts::ConnectedAccount + Sync> ERC20<A> {
    pub fn new(address: starknet::core::types::Felt, account: A) -> Self {
        Self {
            address,
            account,
            block_id: starknet::core::types::BlockId::Tag(
                starknet::core::types::BlockTag::PreConfirmed,
            ),
        }
    }
    pub fn set_contract_address(&mut self, address: starknet::core::types::Felt) {
        self.address = address;
    }
    pub fn provider(&self) -> &A::Provider {
        self.account.provider()
    }
    pub fn set_block(&mut self, block_id: starknet::core::types::BlockId) {
        self.block_id = block_id;
    }
    pub fn with_block(self, block_id: starknet::core::types::BlockId) -> Self {
        Self { block_id, ..self }
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn total_supply(
        &self,
    ) -> cainome_cairo_serde::call::FCall<A::Provider, cainome_cairo_serde::U256> {
        use cainome_cairo_serde::CairoSerde;
        let mut __calldata = vec![];
        let __call = starknet::core::types::FunctionCall {
            contract_address: self.address,
            entry_point_selector: starknet::macros::selector!("total_supply"),
            calldata: __calldata,
        };
        cainome_cairo_serde::call::FCall::new(__call, self.provider())
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn balance_of(
        &self,
        account: &cainome_cairo_serde::ContractAddress,
    ) -> cainome_cairo_serde::call::FCall<A::Provider, cainome_cairo_serde::U256> {
        use cainome_cairo_serde::CairoSerde;
        let mut __calldata = vec![];
        __calldata.extend(cainome_cairo_serde::ContractAddress::cairo_serialize(
            account,
        ));
        let __call = starknet::core::types::FunctionCall {
            contract_address: self.address,
            entry_point_selector: starknet::macros::selector!("balance_of"),
            calldata: __calldata,
        };
        cainome_cairo_serde::call::FCall::new(__call, self.provider())
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn allowance(
        &self,
        owner: &cainome_cairo_serde::ContractAddress,
        spender: &cainome_cairo_serde::ContractAddress,
    ) -> cainome_cairo_serde::call::FCall<A::Provider, cainome_cairo_serde::U256> {
        use cainome_cairo_serde::CairoSerde;
        let mut __calldata = vec![];
        __calldata.extend(cainome_cairo_serde::ContractAddress::cairo_serialize(owner));
        __calldata.extend(cainome_cairo_serde::ContractAddress::cairo_serialize(
            spender,
        ));
        let __call = starknet::core::types::FunctionCall {
            contract_address: self.address,
            entry_point_selector: starknet::macros::selector!("allowance"),
            calldata: __calldata,
        };
        cainome_cairo_serde::call::FCall::new(__call, self.provider())
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn totalSupply(
        &self,
    ) -> cainome_cairo_serde::call::FCall<A::Provider, cainome_cairo_serde::U256> {
        use cainome_cairo_serde::CairoSerde;
        let mut __calldata = vec![];
        let __call = starknet::core::types::FunctionCall {
            contract_address: self.address,
            entry_point_selector: starknet::macros::selector!("totalSupply"),
            calldata: __calldata,
        };
        cainome_cairo_serde::call::FCall::new(__call, self.provider())
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn balanceOf(
        &self,
        account: &cainome_cairo_serde::ContractAddress,
    ) -> cainome_cairo_serde::call::FCall<A::Provider, cainome_cairo_serde::U256> {
        use cainome_cairo_serde::CairoSerde;
        let mut __calldata = vec![];
        __calldata.extend(cainome_cairo_serde::ContractAddress::cairo_serialize(
            account,
        ));
        let __call = starknet::core::types::FunctionCall {
            contract_address: self.address,
            entry_point_selector: starknet::macros::selector!("balanceOf"),
            calldata: __calldata,
        };
        cainome_cairo_serde::call::FCall::new(__call, self.provider())
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn owner(
        &self,
    ) -> cainome_cairo_serde::call::FCall<A::Provider, cainome_cairo_serde::ContractAddress> {
        use cainome_cairo_serde::CairoSerde;
        let mut __calldata = vec![];
        let __call = starknet::core::types::FunctionCall {
            contract_address: self.address,
            entry_point_selector: starknet::macros::selector!("owner"),
            calldata: __calldata,
        };
        cainome_cairo_serde::call::FCall::new(__call, self.provider())
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn name(
        &self,
    ) -> cainome_cairo_serde::call::FCall<A::Provider, starknet::core::types::Felt> {
        use cainome_cairo_serde::CairoSerde;
        let mut __calldata = vec![];
        let __call = starknet::core::types::FunctionCall {
            contract_address: self.address,
            entry_point_selector: starknet::macros::selector!("name"),
            calldata: __calldata,
        };
        cainome_cairo_serde::call::FCall::new(__call, self.provider())
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn symbol(
        &self,
    ) -> cainome_cairo_serde::call::FCall<A::Provider, starknet::core::types::Felt> {
        use cainome_cairo_serde::CairoSerde;
        let mut __calldata = vec![];
        let __call = starknet::core::types::FunctionCall {
            contract_address: self.address,
            entry_point_selector: starknet::macros::selector!("symbol"),
            calldata: __calldata,
        };
        cainome_cairo_serde::call::FCall::new(__call, self.provider())
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn decimals(&self) -> cainome_cairo_serde::call::FCall<A::Provider, u8> {
        use cainome_cairo_serde::CairoSerde;
        let mut __calldata = vec![];
        let __call = starknet::core::types::FunctionCall {
            contract_address: self.address,
            entry_point_selector: starknet::macros::selector!("decimals"),
            calldata: __calldata,
        };
        cainome_cairo_serde::call::FCall::new(__call, self.provider())
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn transfer_getcall(
        &self,
        recipient: &cainome_cairo_serde::ContractAddress,
        amount: &cainome_cairo_serde::U256,
    ) -> starknet::core::types::Call {
        use cainome_cairo_serde::CairoSerde;
        let mut __calldata = vec![];
        __calldata.extend(cainome_cairo_serde::ContractAddress::cairo_serialize(
            recipient,
        ));
        __calldata.extend(cainome_cairo_serde::U256::cairo_serialize(amount));
        starknet::core::types::Call {
            to: self.address,
            selector: starknet::macros::selector!("transfer"),
            calldata: __calldata,
        }
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn transfer(
        &self,
        recipient: &cainome_cairo_serde::ContractAddress,
        amount: &cainome_cairo_serde::U256,
    ) -> starknet::accounts::ExecutionV3<A> {
        let __call = self.transfer_getcall(recipient, amount);
        self.account.execute_v3(vec![__call])
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn transfer_from_getcall(
        &self,
        sender: &cainome_cairo_serde::ContractAddress,
        recipient: &cainome_cairo_serde::ContractAddress,
        amount: &cainome_cairo_serde::U256,
    ) -> starknet::core::types::Call {
        use cainome_cairo_serde::CairoSerde;
        let mut __calldata = vec![];
        __calldata.extend(cainome_cairo_serde::ContractAddress::cairo_serialize(
            sender,
        ));
        __calldata.extend(cainome_cairo_serde::ContractAddress::cairo_serialize(
            recipient,
        ));
        __calldata.extend(cainome_cairo_serde::U256::cairo_serialize(amount));
        starknet::core::types::Call {
            to: self.address,
            selector: starknet::macros::selector!("transfer_from"),
            calldata: __calldata,
        }
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn transfer_from(
        &self,
        sender: &cainome_cairo_serde::ContractAddress,
        recipient: &cainome_cairo_serde::ContractAddress,
        amount: &cainome_cairo_serde::U256,
    ) -> starknet::accounts::ExecutionV3<A> {
        let __call = self.transfer_from_getcall(sender, recipient, amount);
        self.account.execute_v3(vec![__call])
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn approve_getcall(
        &self,
        spender: &cainome_cairo_serde::ContractAddress,
        amount: &cainome_cairo_serde::U256,
    ) -> starknet::core::types::Call {
        use cainome_cairo_serde::CairoSerde;
        let mut __calldata = vec![];
        __calldata.extend(cainome_cairo_serde::ContractAddress::cairo_serialize(
            spender,
        ));
        __calldata.extend(cainome_cairo_serde::U256::cairo_serialize(amount));
        starknet::core::types::Call {
            to: self.address,
            selector: starknet::macros::selector!("approve"),
            calldata: __calldata,
        }
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn approve(
        &self,
        spender: &cainome_cairo_serde::ContractAddress,
        amount: &cainome_cairo_serde::U256,
    ) -> starknet::accounts::ExecutionV3<A> {
        let __call = self.approve_getcall(spender, amount);
        self.account.execute_v3(vec![__call])
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn transferFrom_getcall(
        &self,
        sender: &cainome_cairo_serde::ContractAddress,
        recipient: &cainome_cairo_serde::ContractAddress,
        amount: &cainome_cairo_serde::U256,
    ) -> starknet::core::types::Call {
        use cainome_cairo_serde::CairoSerde;
        let mut __calldata = vec![];
        __calldata.extend(cainome_cairo_serde::ContractAddress::cairo_serialize(
            sender,
        ));
        __calldata.extend(cainome_cairo_serde::ContractAddress::cairo_serialize(
            recipient,
        ));
        __calldata.extend(cainome_cairo_serde::U256::cairo_serialize(amount));
        starknet::core::types::Call {
            to: self.address,
            selector: starknet::macros::selector!("transferFrom"),
            calldata: __calldata,
        }
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn transferFrom(
        &self,
        sender: &cainome_cairo_serde::ContractAddress,
        recipient: &cainome_cairo_serde::ContractAddress,
        amount: &cainome_cairo_serde::U256,
    ) -> starknet::accounts::ExecutionV3<A> {
        let __call = self.transferFrom_getcall(sender, recipient, amount);
        self.account.execute_v3(vec![__call])
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn transferOwnership_getcall(
        &self,
        newOwner: &cainome_cairo_serde::ContractAddress,
    ) -> starknet::core::types::Call {
        use cainome_cairo_serde::CairoSerde;
        let mut __calldata = vec![];
        __calldata.extend(cainome_cairo_serde::ContractAddress::cairo_serialize(
            newOwner,
        ));
        starknet::core::types::Call {
            to: self.address,
            selector: starknet::macros::selector!("transferOwnership"),
            calldata: __calldata,
        }
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn transferOwnership(
        &self,
        newOwner: &cainome_cairo_serde::ContractAddress,
    ) -> starknet::accounts::ExecutionV3<A> {
        let __call = self.transferOwnership_getcall(newOwner);
        self.account.execute_v3(vec![__call])
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn renounceOwnership_getcall(&self) -> starknet::core::types::Call {
        use cainome_cairo_serde::CairoSerde;
        let mut __calldata = vec![];
        starknet::core::types::Call {
            to: self.address,
            selector: starknet::macros::selector!("renounceOwnership"),
            calldata: __calldata,
        }
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn renounceOwnership(&self) -> starknet::accounts::ExecutionV3<A> {
        let __call = self.renounceOwnership_getcall();
        self.account.execute_v3(vec![__call])
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn transfer_ownership_getcall(
        &self,
        new_owner: &cainome_cairo_serde::ContractAddress,
    ) -> starknet::core::types::Call {
        use cainome_cairo_serde::CairoSerde;
        let mut __calldata = vec![];
        __calldata.extend(cainome_cairo_serde::ContractAddress::cairo_serialize(
            new_owner,
        ));
        starknet::core::types::Call {
            to: self.address,
            selector: starknet::macros::selector!("transfer_ownership"),
            calldata: __calldata,
        }
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn transfer_ownership(
        &self,
        new_owner: &cainome_cairo_serde::ContractAddress,
    ) -> starknet::accounts::ExecutionV3<A> {
        let __call = self.transfer_ownership_getcall(new_owner);
        self.account.execute_v3(vec![__call])
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn renounce_ownership_getcall(&self) -> starknet::core::types::Call {
        use cainome_cairo_serde::CairoSerde;
        let mut __calldata = vec![];
        starknet::core::types::Call {
            to: self.address,
            selector: starknet::macros::selector!("renounce_ownership"),
            calldata: __calldata,
        }
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn renounce_ownership(&self) -> starknet::accounts::ExecutionV3<A> {
        let __call = self.renounce_ownership_getcall();
        self.account.execute_v3(vec![__call])
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn mint_getcall(
        &self,
        recipient: &cainome_cairo_serde::ContractAddress,
        amount: &cainome_cairo_serde::U256,
    ) -> starknet::core::types::Call {
        use cainome_cairo_serde::CairoSerde;
        let mut __calldata = vec![];
        __calldata.extend(cainome_cairo_serde::ContractAddress::cairo_serialize(
            recipient,
        ));
        __calldata.extend(cainome_cairo_serde::U256::cairo_serialize(amount));
        starknet::core::types::Call {
            to: self.address,
            selector: starknet::macros::selector!("mint"),
            calldata: __calldata,
        }
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn mint(
        &self,
        recipient: &cainome_cairo_serde::ContractAddress,
        amount: &cainome_cairo_serde::U256,
    ) -> starknet::accounts::ExecutionV3<A> {
        let __call = self.mint_getcall(recipient, amount);
        self.account.execute_v3(vec![__call])
    }
    pub async fn declare(
        path: &std::path::Path,
        account: &A,
        use_blake2s_class_hash: bool,
    ) -> Result<starknet::core::types::Felt, Box<dyn std::error::Error>>
    where
        A::SignError: 'static,
    {
        use starknet_api::contract_class::compiled_class_hash::HashableCompiledClass;
        let sierra_class: cairo_lang_starknet_classes::contract_class::ContractClass =
            serde_json::from_slice::<cairo_lang_starknet_classes::contract_class::ContractClass>(
                std::fs::read(path)?.as_slice(),
            )?;
        let casm_class = cairo_lang_starknet_classes::casm_contract_class::CasmContractClass::from_contract_class(
            sierra_class,
            false,
            180000usize,
        )?;
        let hash_version = if use_blake2s_class_hash {
            starknet_api::contract_class::compiled_class_hash::HashVersion::V2
        } else {
            starknet_api::contract_class::compiled_class_hash::HashVersion::V1
        };
        let class_hash = starknet::core::types::Felt::from_bytes_be(
            &casm_class.hash(&hash_version).0.to_bytes_be(),
        );
        let contract_artifact: starknet::core::types::contract::SierraClass =
            serde_json::from_reader(std::fs::File::open(path)?)?;
        let declaration = account.declare_v3(
            std::sync::Arc::new(contract_artifact.flatten()?),
            class_hash,
        );
        let declaration_result = declaration.send().await?;
        Ok(declaration_result.class_hash)
    }
    pub async fn deploy(
        udc_selector: starknet::contract::UdcSelector,
        account: A,
        class_hash: starknet::core::types::Felt,
        calldata: &ERC20Calldata,
    ) -> Result<Self, Box<dyn std::error::Error>>
    where
        A::SignError: 'static,
    {
        use cainome_cairo_serde::CairoSerde;
        let generate_salt = true;
        let is_unique = true;
        let salt: starknet::core::types::Felt = if generate_salt {
            use rand::Rng;
            rand::rng().random::<u128>().into()
        } else {
            starknet::core::types::Felt::ZERO
        };
        let factory =
            starknet::contract::ContractFactory::new_with_udc(class_hash, &account, udc_selector);
        let deployment =
            factory.deploy_v3(ERC20Calldata::cairo_serialize(&calldata), salt, is_unique);
        let deployed_address = deployment.deployed_address();
        let tx = deployment.send().await?;
        Ok(Self::new(deployed_address, account))
    }
}
pub struct ERC20Reader<P: starknet::providers::Provider + Sync> {
    pub address: starknet::core::types::Felt,
    pub provider: P,
    pub block_id: starknet::core::types::BlockId,
}
impl<P: starknet::providers::Provider + Sync> ERC20Reader<P> {
    pub fn new(address: starknet::core::types::Felt, provider: P) -> Self {
        Self {
            address,
            provider,
            block_id: starknet::core::types::BlockId::Tag(
                starknet::core::types::BlockTag::PreConfirmed,
            ),
        }
    }
    pub fn set_contract_address(&mut self, address: starknet::core::types::Felt) {
        self.address = address;
    }
    pub fn provider(&self) -> &P {
        &self.provider
    }
    pub fn set_block(&mut self, block_id: starknet::core::types::BlockId) {
        self.block_id = block_id;
    }
    pub fn with_block(self, block_id: starknet::core::types::BlockId) -> Self {
        Self { block_id, ..self }
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn total_supply(&self) -> cainome_cairo_serde::call::FCall<P, cainome_cairo_serde::U256> {
        use cainome_cairo_serde::CairoSerde;
        let mut __calldata = vec![];
        let __call = starknet::core::types::FunctionCall {
            contract_address: self.address,
            entry_point_selector: starknet::macros::selector!("total_supply"),
            calldata: __calldata,
        };
        cainome_cairo_serde::call::FCall::new(__call, self.provider())
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn balance_of(
        &self,
        account: &cainome_cairo_serde::ContractAddress,
    ) -> cainome_cairo_serde::call::FCall<P, cainome_cairo_serde::U256> {
        use cainome_cairo_serde::CairoSerde;
        let mut __calldata = vec![];
        __calldata.extend(cainome_cairo_serde::ContractAddress::cairo_serialize(
            account,
        ));
        let __call = starknet::core::types::FunctionCall {
            contract_address: self.address,
            entry_point_selector: starknet::macros::selector!("balance_of"),
            calldata: __calldata,
        };
        cainome_cairo_serde::call::FCall::new(__call, self.provider())
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn allowance(
        &self,
        owner: &cainome_cairo_serde::ContractAddress,
        spender: &cainome_cairo_serde::ContractAddress,
    ) -> cainome_cairo_serde::call::FCall<P, cainome_cairo_serde::U256> {
        use cainome_cairo_serde::CairoSerde;
        let mut __calldata = vec![];
        __calldata.extend(cainome_cairo_serde::ContractAddress::cairo_serialize(owner));
        __calldata.extend(cainome_cairo_serde::ContractAddress::cairo_serialize(
            spender,
        ));
        let __call = starknet::core::types::FunctionCall {
            contract_address: self.address,
            entry_point_selector: starknet::macros::selector!("allowance"),
            calldata: __calldata,
        };
        cainome_cairo_serde::call::FCall::new(__call, self.provider())
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn totalSupply(&self) -> cainome_cairo_serde::call::FCall<P, cainome_cairo_serde::U256> {
        use cainome_cairo_serde::CairoSerde;
        let mut __calldata = vec![];
        let __call = starknet::core::types::FunctionCall {
            contract_address: self.address,
            entry_point_selector: starknet::macros::selector!("totalSupply"),
            calldata: __calldata,
        };
        cainome_cairo_serde::call::FCall::new(__call, self.provider())
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn balanceOf(
        &self,
        account: &cainome_cairo_serde::ContractAddress,
    ) -> cainome_cairo_serde::call::FCall<P, cainome_cairo_serde::U256> {
        use cainome_cairo_serde::CairoSerde;
        let mut __calldata = vec![];
        __calldata.extend(cainome_cairo_serde::ContractAddress::cairo_serialize(
            account,
        ));
        let __call = starknet::core::types::FunctionCall {
            contract_address: self.address,
            entry_point_selector: starknet::macros::selector!("balanceOf"),
            calldata: __calldata,
        };
        cainome_cairo_serde::call::FCall::new(__call, self.provider())
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn owner(
        &self,
    ) -> cainome_cairo_serde::call::FCall<P, cainome_cairo_serde::ContractAddress> {
        use cainome_cairo_serde::CairoSerde;
        let mut __calldata = vec![];
        let __call = starknet::core::types::FunctionCall {
            contract_address: self.address,
            entry_point_selector: starknet::macros::selector!("owner"),
            calldata: __calldata,
        };
        cainome_cairo_serde::call::FCall::new(__call, self.provider())
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn name(&self) -> cainome_cairo_serde::call::FCall<P, starknet::core::types::Felt> {
        use cainome_cairo_serde::CairoSerde;
        let mut __calldata = vec![];
        let __call = starknet::core::types::FunctionCall {
            contract_address: self.address,
            entry_point_selector: starknet::macros::selector!("name"),
            calldata: __calldata,
        };
        cainome_cairo_serde::call::FCall::new(__call, self.provider())
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn symbol(&self) -> cainome_cairo_serde::call::FCall<P, starknet::core::types::Felt> {
        use cainome_cairo_serde::CairoSerde;
        let mut __calldata = vec![];
        let __call = starknet::core::types::FunctionCall {
            contract_address: self.address,
            entry_point_selector: starknet::macros::selector!("symbol"),
            calldata: __calldata,
        };
        cainome_cairo_serde::call::FCall::new(__call, self.provider())
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn decimals(&self) -> cainome_cairo_serde::call::FCall<P, u8> {
        use cainome_cairo_serde::CairoSerde;
        let mut __calldata = vec![];
        let __call = starknet::core::types::FunctionCall {
            contract_address: self.address,
            entry_point_selector: starknet::macros::selector!("decimals"),
            calldata: __calldata,
        };
        cainome_cairo_serde::call::FCall::new(__call, self.provider())
    }
}
