// ****
// Auto-generated by cainome do not edit.
// ****

#![allow(clippy::all)]
#![allow(warnings)]

pub mod contracts {
    pub mod simple_get_set {
        pub mod simple_get_set {
            pub enum Event {}
            impl cainome_cairo_serde::CairoSerde for Event {
                type RustType = Self;
                const SERIALIZED_SIZE: std::option::Option<usize> = std::option::Option::None;
                #[inline]
                fn cairo_serialized_size(__rust: &Self::RustType) -> usize {
                    match __rust {
                        _ => 0,
                    }
                }
                fn cairo_serialize(__rust: &Self::RustType) -> Vec<starknet::core::types::Felt> {
                    match __rust {
                        _ => vec![],
                    }
                }
                fn cairo_deserialize(
                    __felts: &[starknet::core::types::Felt],
                    __offset: usize,
                ) -> cainome_cairo_serde::Result<Self::RustType> {
                    let __f = __felts[__offset];
                    let __index = u128::from_be_bytes(__f.to_bytes_be()[16..].try_into().unwrap());
                    match __index as usize {
                        _ => {
                            return Err(cainome_cairo_serde::Error::Deserialize(format!(
                                "Index not handle for enum {}",
                                "Event"
                            )));
                        }
                    }
                }
            }
            impl Event {
                pub(crate) fn try_from_event(
                    from_address: starknet::core::types::Felt,
                    keys: Vec<starknet::core::types::Felt>,
                    data: Vec<starknet::core::types::Felt>,
                ) -> Result<Self, String> {
                    if keys.is_empty() {
                        return Err("Event has no key".to_string());
                    }
                    use cainome_cairo_serde::CairoSerde;
                    Err(format!("Could not match any event from keys {:?}", keys))
                }
            }
            impl TryFrom<starknet::core::types::EmittedEvent> for Event {
                type Error = String;
                fn try_from(
                    event: starknet::core::types::EmittedEvent,
                ) -> Result<Self, Self::Error> {
                    Self::try_from_event(event.from_address, event.keys, event.data)
                }
            }
            impl TryFrom<starknet::core::types::Event> for Event {
                type Error = String;
                fn try_from(event: starknet::core::types::Event) -> Result<Self, Self::Error> {
                    Self::try_from_event(event.from_address, event.keys, event.data)
                }
            }
            pub enum TestEnum {
                V1(starknet::core::types::Felt),
                V2,
            }
            impl cainome_cairo_serde::CairoSerde for TestEnum {
                type RustType = Self;
                const SERIALIZED_SIZE: std::option::Option<usize> = std::option::Option::None;
                #[inline]
                fn cairo_serialized_size(__rust: &Self::RustType) -> usize {
                    match __rust {
                        TestEnum::V1(val) => {
                            starknet::core::types::Felt::cairo_serialized_size(val) + 1
                        }
                        TestEnum::V2 => 1,
                        _ => 0,
                    }
                }
                fn cairo_serialize(__rust: &Self::RustType) -> Vec<starknet::core::types::Felt> {
                    match __rust {
                        TestEnum::V1(val) => {
                            let mut temp = vec![];
                            temp.extend(usize::cairo_serialize(&0usize));
                            temp.extend(starknet::core::types::Felt::cairo_serialize(val));
                            temp
                        }
                        TestEnum::V2 => usize::cairo_serialize(&1usize),
                        _ => vec![],
                    }
                }
                fn cairo_deserialize(
                    __felts: &[starknet::core::types::Felt],
                    __offset: usize,
                ) -> cainome_cairo_serde::Result<Self::RustType> {
                    let __f = __felts[__offset];
                    let __index = u128::from_be_bytes(__f.to_bytes_be()[16..].try_into().unwrap());
                    match __index as usize {
                        0usize => Ok(TestEnum::V1(
                            starknet::core::types::Felt::cairo_deserialize(__felts, __offset + 1)?,
                        )),
                        1usize => Ok(TestEnum::V2),
                        _ => {
                            return Err(cainome_cairo_serde::Error::Deserialize(format!(
                                "Index not handle for enum {}",
                                "TestEnum"
                            )));
                        }
                    }
                }
            }
        }
    }
}
pub mod core {
    pub mod array {
        pub struct Span {
            pub snapshot: Vec<starknet::core::types::Felt>,
        }
        impl cainome_cairo_serde::CairoSerde for Span {
            type RustType = Self;
            const SERIALIZED_SIZE: std::option::Option<usize> = None;
            #[inline]
            fn cairo_serialized_size(__rust: &Self::RustType) -> usize {
                let mut __size = 0;
                __size +=
                    Vec::<starknet::core::types::Felt>::cairo_serialized_size(&__rust.snapshot);
                __size
            }
            fn cairo_serialize(__rust: &Self::RustType) -> Vec<starknet::core::types::Felt> {
                let mut __out: Vec<starknet::core::types::Felt> = vec![];
                __out.extend(Vec::<starknet::core::types::Felt>::cairo_serialize(
                    &__rust.snapshot,
                ));
                __out
            }
            fn cairo_deserialize(
                __felts: &[starknet::core::types::Felt],
                __offset: usize,
            ) -> cainome_cairo_serde::Result<Self::RustType> {
                let mut __offset = __offset;
                let snapshot =
                    Vec::<starknet::core::types::Felt>::cairo_deserialize(__felts, __offset)?;
                __offset += Vec::<starknet::core::types::Felt>::cairo_serialized_size(&snapshot);
                Ok(Span { snapshot })
            }
        }
    }
}
pub struct SimpleGetSet<A: starknet::accounts::ConnectedAccount + Sync> {
    pub address: starknet::core::types::Felt,
    pub account: A,
    pub block_id: starknet::core::types::BlockId,
}
impl<A: starknet::accounts::ConnectedAccount + Sync> SimpleGetSet<A> {
    pub fn new(address: starknet::core::types::Felt, account: A) -> Self {
        Self {
            address,
            account,
            block_id: starknet::core::types::BlockId::Tag(
                starknet::core::types::BlockTag::PreConfirmed,
            ),
        }
    }
    pub fn set_contract_address(&mut self, address: starknet::core::types::Felt) {
        self.address = address;
    }
    pub fn provider(&self) -> &A::Provider {
        self.account.provider()
    }
    pub fn set_block(&mut self, block_id: starknet::core::types::BlockId) {
        self.block_id = block_id;
    }
    pub fn with_block(self, block_id: starknet::core::types::BlockId) -> Self {
        Self { block_id, ..self }
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn get_array(
        &self,
    ) -> cainome_cairo_serde::call::FCall<A::Provider, Vec<starknet::core::types::Felt>> {
        use cainome_cairo_serde::CairoSerde;
        let mut __calldata = vec![];
        let __call = starknet::core::types::FunctionCall {
            contract_address: self.address,
            entry_point_selector: starknet::macros::selector!("get_array"),
            calldata: __calldata,
        };
        cainome_cairo_serde::call::FCall::new(__call, self.provider())
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn get_b(
        &self,
    ) -> cainome_cairo_serde::call::FCall<A::Provider, cainome_cairo_serde::U256> {
        use cainome_cairo_serde::CairoSerde;
        let mut __calldata = vec![];
        let __call = starknet::core::types::FunctionCall {
            contract_address: self.address,
            entry_point_selector: starknet::macros::selector!("get_b"),
            calldata: __calldata,
        };
        cainome_cairo_serde::call::FCall::new(__call, self.provider())
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn get_set_enum(
        &self,
        v: &crate::bindings::simple_get_set::contracts::simple_get_set::simple_get_set::TestEnum,
    ) -> cainome_cairo_serde::call::FCall<
        A::Provider,
        crate::bindings::simple_get_set::contracts::simple_get_set::simple_get_set::TestEnum,
    > {
        use cainome_cairo_serde::CairoSerde;
        let mut __calldata = vec![];
        __calldata
            .extend(
                crate::bindings::simple_get_set::contracts::simple_get_set::simple_get_set::TestEnum::cairo_serialize(
                    v,
                ),
            );
        let __call = starknet::core::types::FunctionCall {
            contract_address: self.address,
            entry_point_selector: starknet::macros::selector!("get_set_enum"),
            calldata: __calldata,
        };
        cainome_cairo_serde::call::FCall::new(__call, self.provider())
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn get_a(
        &self,
    ) -> cainome_cairo_serde::call::FCall<A::Provider, starknet::core::types::Felt> {
        use cainome_cairo_serde::CairoSerde;
        let mut __calldata = vec![];
        let __call = starknet::core::types::FunctionCall {
            contract_address: self.address,
            entry_point_selector: starknet::macros::selector!("get_a"),
            calldata: __calldata,
        };
        cainome_cairo_serde::call::FCall::new(__call, self.provider())
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn set_a_getcall(&self, a: &starknet::core::types::Felt) -> starknet::core::types::Call {
        use cainome_cairo_serde::CairoSerde;
        let mut __calldata = vec![];
        __calldata.extend(starknet::core::types::Felt::cairo_serialize(a));
        starknet::core::types::Call {
            to: self.address,
            selector: starknet::macros::selector!("set_a"),
            calldata: __calldata,
        }
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn set_a(&self, a: &starknet::core::types::Felt) -> starknet::accounts::ExecutionV3<A> {
        let __call = self.set_a_getcall(a);
        self.account.execute_v3(vec![__call])
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn set_b_getcall(&self, b: &cainome_cairo_serde::U256) -> starknet::core::types::Call {
        use cainome_cairo_serde::CairoSerde;
        let mut __calldata = vec![];
        __calldata.extend(cainome_cairo_serde::U256::cairo_serialize(b));
        starknet::core::types::Call {
            to: self.address,
            selector: starknet::macros::selector!("set_b"),
            calldata: __calldata,
        }
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn set_b(&self, b: &cainome_cairo_serde::U256) -> starknet::accounts::ExecutionV3<A> {
        let __call = self.set_b_getcall(b);
        self.account.execute_v3(vec![__call])
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn set_array_getcall(
        &self,
        data: &Vec<starknet::core::types::Felt>,
    ) -> starknet::core::types::Call {
        use cainome_cairo_serde::CairoSerde;
        let mut __calldata = vec![];
        __calldata.extend(Vec::<starknet::core::types::Felt>::cairo_serialize(data));
        starknet::core::types::Call {
            to: self.address,
            selector: starknet::macros::selector!("set_array"),
            calldata: __calldata,
        }
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn set_array(
        &self,
        data: &Vec<starknet::core::types::Felt>,
    ) -> starknet::accounts::ExecutionV3<A> {
        let __call = self.set_array_getcall(data);
        self.account.execute_v3(vec![__call])
    }
    pub async fn declare(
        path: &std::path::Path,
        account: &A,
    ) -> Result<starknet::core::types::Felt, Box<dyn std::error::Error>>
    where
        A::SignError: 'static,
    {
        let sierra_class: cairo_lang_starknet_classes::contract_class::ContractClass =
            serde_json::from_slice::<cairo_lang_starknet_classes::contract_class::ContractClass>(
                std::fs::read(path)?.as_slice(),
            )?;
        let casm_class = cairo_lang_starknet_classes::casm_contract_class::CasmContractClass::from_contract_class(
            sierra_class,
            false,
            180000usize,
        )?;
        let class_hash = starknet::core::types::Felt::from_bytes_be(
            &casm_class.compiled_class_hash().to_bytes_be(),
        );
        let contract_artifact: starknet::core::types::contract::SierraClass =
            serde_json::from_reader(std::fs::File::open(path)?)?;
        let declaration = account.declare_v3(
            std::sync::Arc::new(contract_artifact.flatten()?),
            class_hash,
        );
        let declaration_result = declaration.send().await?;
        Ok(declaration_result.class_hash)
    }
    pub async fn deploy(
        deployer_address: starknet::core::types::Felt,
        account: A,
        class_hash: starknet::core::types::Felt,
        constructor_calldata: Vec<starknet::core::types::Felt>,
    ) -> Result<Self, Box<dyn std::error::Error>> {
        let generate_salt = true;
        let is_unique = true;
        let salt: starknet::core::types::Felt = if generate_salt {
            use rand::Rng;
            rand::rng().random::<u128>().into()
        } else {
            starknet::core::types::Felt::ZERO
        };
        let calldata = [
            vec![
                class_hash,
                salt,
                starknet::core::types::Felt::from(is_unique),
                starknet::core::types::Felt::from(constructor_calldata.len()),
            ]
            .as_slice(),
            constructor_calldata.as_slice(),
        ]
        .concat();
        let tx = account
            .execute_v3(vec![starknet::core::types::Call {
                to: deployer_address,
                selector: starknet::macros::selector!("deployContract"),
                calldata: calldata,
            }])
            .send()
            .await
            .unwrap();
        let uniqueness = if is_unique {
            &starknet::core::utils::UdcUniqueness::Unique(
                starknet::core::utils::UdcUniqueSettings {
                    udc_contract_address: deployer_address,
                    deployer_address: account.address(),
                },
            )
        } else {
            &starknet::core::utils::UdcUniqueness::NotUnique
        };
        let deployed_address = starknet::core::utils::get_udc_deployed_address(
            salt,
            class_hash,
            uniqueness,
            constructor_calldata.as_slice(),
        );
        Ok(Self::new(deployed_address, account))
    }
}
pub struct SimpleGetSetReader<P: starknet::providers::Provider + Sync> {
    pub address: starknet::core::types::Felt,
    pub provider: P,
    pub block_id: starknet::core::types::BlockId,
}
impl<P: starknet::providers::Provider + Sync> SimpleGetSetReader<P> {
    pub fn new(address: starknet::core::types::Felt, provider: P) -> Self {
        Self {
            address,
            provider,
            block_id: starknet::core::types::BlockId::Tag(
                starknet::core::types::BlockTag::PreConfirmed,
            ),
        }
    }
    pub fn set_contract_address(&mut self, address: starknet::core::types::Felt) {
        self.address = address;
    }
    pub fn provider(&self) -> &P {
        &self.provider
    }
    pub fn set_block(&mut self, block_id: starknet::core::types::BlockId) {
        self.block_id = block_id;
    }
    pub fn with_block(self, block_id: starknet::core::types::BlockId) -> Self {
        Self { block_id, ..self }
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn get_array(
        &self,
    ) -> cainome_cairo_serde::call::FCall<P, Vec<starknet::core::types::Felt>> {
        use cainome_cairo_serde::CairoSerde;
        let mut __calldata = vec![];
        let __call = starknet::core::types::FunctionCall {
            contract_address: self.address,
            entry_point_selector: starknet::macros::selector!("get_array"),
            calldata: __calldata,
        };
        cainome_cairo_serde::call::FCall::new(__call, self.provider())
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn get_b(&self) -> cainome_cairo_serde::call::FCall<P, cainome_cairo_serde::U256> {
        use cainome_cairo_serde::CairoSerde;
        let mut __calldata = vec![];
        let __call = starknet::core::types::FunctionCall {
            contract_address: self.address,
            entry_point_selector: starknet::macros::selector!("get_b"),
            calldata: __calldata,
        };
        cainome_cairo_serde::call::FCall::new(__call, self.provider())
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn get_set_enum(
        &self,
        v: &crate::bindings::simple_get_set::contracts::simple_get_set::simple_get_set::TestEnum,
    ) -> cainome_cairo_serde::call::FCall<
        P,
        crate::bindings::simple_get_set::contracts::simple_get_set::simple_get_set::TestEnum,
    > {
        use cainome_cairo_serde::CairoSerde;
        let mut __calldata = vec![];
        __calldata
            .extend(
                crate::bindings::simple_get_set::contracts::simple_get_set::simple_get_set::TestEnum::cairo_serialize(
                    v,
                ),
            );
        let __call = starknet::core::types::FunctionCall {
            contract_address: self.address,
            entry_point_selector: starknet::macros::selector!("get_set_enum"),
            calldata: __calldata,
        };
        cainome_cairo_serde::call::FCall::new(__call, self.provider())
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn get_a(&self) -> cainome_cairo_serde::call::FCall<P, starknet::core::types::Felt> {
        use cainome_cairo_serde::CairoSerde;
        let mut __calldata = vec![];
        let __call = starknet::core::types::FunctionCall {
            contract_address: self.address,
            entry_point_selector: starknet::macros::selector!("get_a"),
            calldata: __calldata,
        };
        cainome_cairo_serde::call::FCall::new(__call, self.provider())
    }
}
