// ****
// Auto-generated by cainome do not edit.
// ****

#![allow(clippy::all)]
#![allow(warnings)]

pub mod contracts {
    pub mod gen {
        pub mod gen {
            #[derive(Clone, Debug, PartialEq, serde::Deserialize, serde::Serialize)]
            pub struct MyStructInnerGeneric {
                pub f1: starknet::core::types::Felt,
                pub f2: crate::bindings::structs::contracts::gen::gen::MyStruct,
                pub f3: u32,
            }
            impl cainome_cairo_serde::CairoSerde for MyStructInnerGeneric {
                type RustType = Self;
                const SERIALIZED_SIZE: std::option::Option<usize> = None;
                #[inline]
                fn cairo_serialized_size(__rust: &Self::RustType) -> usize {
                    let mut __size = 0;
                    __size += starknet::core::types::Felt::cairo_serialized_size(&__rust.f1);
                    __size
                        += crate::bindings::structs::contracts::gen::gen::MyStruct::cairo_serialized_size(
                            &__rust.f2,
                        );
                    __size += u32::cairo_serialized_size(&__rust.f3);
                    __size
                }
                fn cairo_serialize(__rust: &Self::RustType) -> Vec<starknet::core::types::Felt> {
                    let mut __out: Vec<starknet::core::types::Felt> = vec![];
                    __out.extend(starknet::core::types::Felt::cairo_serialize(&__rust.f1));
                    __out.extend(
                        crate::bindings::structs::contracts::gen::gen::MyStruct::cairo_serialize(
                            &__rust.f2,
                        ),
                    );
                    __out.extend(u32::cairo_serialize(&__rust.f3));
                    __out
                }
                fn cairo_deserialize(
                    __felts: &[starknet::core::types::Felt],
                    __offset: usize,
                ) -> cainome_cairo_serde::Result<Self::RustType> {
                    let mut __offset = __offset;
                    let f1 = starknet::core::types::Felt::cairo_deserialize(__felts, __offset)?;
                    __offset += starknet::core::types::Felt::cairo_serialized_size(&f1);
                    let f2 =
                        crate::bindings::structs::contracts::gen::gen::MyStruct::cairo_deserialize(
                            __felts, __offset,
                        )?;
                    __offset
                        += crate::bindings::structs::contracts::gen::gen::MyStruct::cairo_serialized_size(
                            &f2,
                        );
                    let f3 = u32::cairo_deserialize(__felts, __offset)?;
                    __offset += u32::cairo_serialized_size(&f3);
                    Ok(MyStructInnerGeneric { f1, f2, f3 })
                }
            }
            #[derive(Clone, Debug, PartialEq, serde::Deserialize, serde::Serialize)]
            pub struct MyStruct {
                pub f1: starknet::core::types::Felt,
                pub f2: cainome_cairo_serde::U256,
                pub f3: starknet::core::types::Felt,
            }
            impl cainome_cairo_serde::CairoSerde for MyStruct {
                type RustType = Self;
                const SERIALIZED_SIZE: std::option::Option<usize> = None;
                #[inline]
                fn cairo_serialized_size(__rust: &Self::RustType) -> usize {
                    let mut __size = 0;
                    __size += starknet::core::types::Felt::cairo_serialized_size(&__rust.f1);
                    __size += cainome_cairo_serde::U256::cairo_serialized_size(&__rust.f2);
                    __size += starknet::core::types::Felt::cairo_serialized_size(&__rust.f3);
                    __size
                }
                fn cairo_serialize(__rust: &Self::RustType) -> Vec<starknet::core::types::Felt> {
                    let mut __out: Vec<starknet::core::types::Felt> = vec![];
                    __out.extend(starknet::core::types::Felt::cairo_serialize(&__rust.f1));
                    __out.extend(cainome_cairo_serde::U256::cairo_serialize(&__rust.f2));
                    __out.extend(starknet::core::types::Felt::cairo_serialize(&__rust.f3));
                    __out
                }
                fn cairo_deserialize(
                    __felts: &[starknet::core::types::Felt],
                    __offset: usize,
                ) -> cainome_cairo_serde::Result<Self::RustType> {
                    let mut __offset = __offset;
                    let f1 = starknet::core::types::Felt::cairo_deserialize(__felts, __offset)?;
                    __offset += starknet::core::types::Felt::cairo_serialized_size(&f1);
                    let f2 = cainome_cairo_serde::U256::cairo_deserialize(__felts, __offset)?;
                    __offset += cainome_cairo_serde::U256::cairo_serialized_size(&f2);
                    let f3 = starknet::core::types::Felt::cairo_deserialize(__felts, __offset)?;
                    __offset += starknet::core::types::Felt::cairo_serialized_size(&f3);
                    Ok(MyStruct { f1, f2, f3 })
                }
            }
            #[derive(Clone, Debug, PartialEq, serde::Deserialize, serde::Serialize)]
            pub struct PlainStruct {
                pub f1: u8,
                pub f2: u16,
                pub f3: u32,
                #[serde(
                    serialize_with = "cainome_cairo_serde::serialize_as_hex",
                    deserialize_with = "cainome_cairo_serde::deserialize_from_hex"
                )]
                pub f4: u64,
                #[serde(
                    serialize_with = "cainome_cairo_serde::serialize_as_hex",
                    deserialize_with = "cainome_cairo_serde::deserialize_from_hex"
                )]
                pub f5: u128,
                pub f6: starknet::core::types::Felt,
                #[serde(
                    serialize_with = "cainome_cairo_serde::serialize_as_hex_t2",
                    deserialize_with = "cainome_cairo_serde::deserialize_from_hex_t2"
                )]
                pub f7: (starknet::core::types::Felt, u64),
                pub f8: Vec<u8>,
                #[serde(
                    serialize_with = "cainome_cairo_serde::serialize_as_hex_vec",
                    deserialize_with = "cainome_cairo_serde::deserialize_from_hex_vec"
                )]
                pub f9: Vec<u128>,
            }
            impl cainome_cairo_serde::CairoSerde for PlainStruct {
                type RustType = Self;
                const SERIALIZED_SIZE: std::option::Option<usize> = None;
                #[inline]
                fn cairo_serialized_size(__rust: &Self::RustType) -> usize {
                    let mut __size = 0;
                    __size += u8::cairo_serialized_size(&__rust.f1);
                    __size += u16::cairo_serialized_size(&__rust.f2);
                    __size += u32::cairo_serialized_size(&__rust.f3);
                    __size += u64::cairo_serialized_size(&__rust.f4);
                    __size += u128::cairo_serialized_size(&__rust.f5);
                    __size += starknet::core::types::Felt::cairo_serialized_size(&__rust.f6);
                    __size +=
                        <(starknet::core::types::Felt, u64)>::cairo_serialized_size(&__rust.f7);
                    __size += Vec::<u8>::cairo_serialized_size(&__rust.f8);
                    __size += Vec::<u128>::cairo_serialized_size(&__rust.f9);
                    __size
                }
                fn cairo_serialize(__rust: &Self::RustType) -> Vec<starknet::core::types::Felt> {
                    let mut __out: Vec<starknet::core::types::Felt> = vec![];
                    __out.extend(u8::cairo_serialize(&__rust.f1));
                    __out.extend(u16::cairo_serialize(&__rust.f2));
                    __out.extend(u32::cairo_serialize(&__rust.f3));
                    __out.extend(u64::cairo_serialize(&__rust.f4));
                    __out.extend(u128::cairo_serialize(&__rust.f5));
                    __out.extend(starknet::core::types::Felt::cairo_serialize(&__rust.f6));
                    __out.extend(<(starknet::core::types::Felt, u64)>::cairo_serialize(
                        &__rust.f7,
                    ));
                    __out.extend(Vec::<u8>::cairo_serialize(&__rust.f8));
                    __out.extend(Vec::<u128>::cairo_serialize(&__rust.f9));
                    __out
                }
                fn cairo_deserialize(
                    __felts: &[starknet::core::types::Felt],
                    __offset: usize,
                ) -> cainome_cairo_serde::Result<Self::RustType> {
                    let mut __offset = __offset;
                    let f1 = u8::cairo_deserialize(__felts, __offset)?;
                    __offset += u8::cairo_serialized_size(&f1);
                    let f2 = u16::cairo_deserialize(__felts, __offset)?;
                    __offset += u16::cairo_serialized_size(&f2);
                    let f3 = u32::cairo_deserialize(__felts, __offset)?;
                    __offset += u32::cairo_serialized_size(&f3);
                    let f4 = u64::cairo_deserialize(__felts, __offset)?;
                    __offset += u64::cairo_serialized_size(&f4);
                    let f5 = u128::cairo_deserialize(__felts, __offset)?;
                    __offset += u128::cairo_serialized_size(&f5);
                    let f6 = starknet::core::types::Felt::cairo_deserialize(__felts, __offset)?;
                    __offset += starknet::core::types::Felt::cairo_serialized_size(&f6);
                    let f7 =
                        <(starknet::core::types::Felt, u64)>::cairo_deserialize(__felts, __offset)?;
                    __offset += <(starknet::core::types::Felt, u64)>::cairo_serialized_size(&f7);
                    let f8 = Vec::<u8>::cairo_deserialize(__felts, __offset)?;
                    __offset += Vec::<u8>::cairo_serialized_size(&f8);
                    let f9 = Vec::<u128>::cairo_deserialize(__felts, __offset)?;
                    __offset += Vec::<u128>::cairo_serialized_size(&f9);
                    Ok(PlainStruct {
                        f1,
                        f2,
                        f3,
                        f4,
                        f5,
                        f6,
                        f7,
                        f8,
                        f9,
                    })
                }
            }
            #[derive(Clone, Debug, PartialEq, serde::Deserialize, serde::Serialize)]
            pub enum Event {
                E1(crate::bindings::structs::contracts::gen::gen::E1),
            }
            impl cainome_cairo_serde::CairoSerde for Event {
                type RustType = Self;
                const SERIALIZED_SIZE: std::option::Option<usize> = std::option::Option::None;
                #[inline]
                fn cairo_serialized_size(__rust: &Self::RustType) -> usize {
                    match __rust {
                        Event::E1(val) => {
                            crate::bindings::structs::contracts::gen::gen::E1::cairo_serialized_size(
                                val,
                            ) + 1
                        }
                        _ => 0,
                    }
                }
                fn cairo_serialize(__rust: &Self::RustType) -> Vec<starknet::core::types::Felt> {
                    match __rust {
                        Event::E1(val) => {
                            let mut temp = vec![];
                            temp.extend(usize::cairo_serialize(&0usize));
                            temp.extend(
                                crate::bindings::structs::contracts::gen::gen::E1::cairo_serialize(
                                    val,
                                ),
                            );
                            temp
                        }
                        _ => vec![],
                    }
                }
                fn cairo_deserialize(
                    __felts: &[starknet::core::types::Felt],
                    __offset: usize,
                ) -> cainome_cairo_serde::Result<Self::RustType> {
                    let __f = __felts[__offset];
                    let __index = u128::from_be_bytes(__f.to_bytes_be()[16..].try_into().unwrap());
                    match __index as usize {
                        0usize => Ok(Event::E1(
                            crate::bindings::structs::contracts::gen::gen::E1::cairo_deserialize(
                                __felts,
                                __offset + 1,
                            )?,
                        )),
                        _ => {
                            return Err(cainome_cairo_serde::Error::Deserialize(format!(
                                "Index not handle for enum {}",
                                "Event"
                            )));
                        }
                    }
                }
            }
            impl Event {
                pub fn event_selector() -> starknet::core::types::Felt {
                    starknet::core::utils::get_selector_from_name("Event").unwrap()
                }
                pub fn event_name() -> &'static str {
                    "Event"
                }
                pub(crate) fn try_from_event(
                    from_address: starknet::core::types::Felt,
                    keys: Vec<starknet::core::types::Felt>,
                    data: Vec<starknet::core::types::Felt>,
                ) -> Result<Self, String> {
                    if keys.is_empty() {
                        return Err("Event has no key".to_string());
                    }
                    use cainome_cairo_serde::CairoSerde;
                    if keys[0]
                        == starknet::core::utils::get_selector_from_name("E1")
                            .unwrap_or_else(|_| panic!("Invalid selector for {}", "E1"))
                    {
                        let res =
                            crate::bindings::structs::contracts::gen::gen::E1::cairo_deserialize(
                                &data, 0,
                            )
                            .map_err(|e| {
                                format!(
                                    "Could not deserialize {} event data: {:?}",
                                    "crate::bindings::structs::contracts::gen::gen::E1", e
                                )
                            })?;
                        return Ok(Event::E1(res));
                    }
                    Err(format!("Could not match any event from keys {:?}", keys))
                }
            }
            impl TryFrom<starknet::core::types::EmittedEvent> for Event {
                type Error = String;
                fn try_from(
                    event: starknet::core::types::EmittedEvent,
                ) -> Result<Self, Self::Error> {
                    Self::try_from_event(event.from_address, event.keys, event.data)
                }
            }
            impl TryFrom<starknet::core::types::Event> for Event {
                type Error = String;
                fn try_from(event: starknet::core::types::Event) -> Result<Self, Self::Error> {
                    Self::try_from_event(event.from_address, event.keys, event.data)
                }
            }
            #[derive(Clone, Debug, PartialEq, serde::Deserialize, serde::Serialize)]
            pub struct E1 {
                pub key: starknet::core::types::Felt,
                pub value: Vec<starknet::core::types::Felt>,
            }
            impl cainome_cairo_serde::CairoSerde for E1 {
                type RustType = Self;
                const SERIALIZED_SIZE: std::option::Option<usize> = None;
                #[inline]
                fn cairo_serialized_size(__rust: &Self::RustType) -> usize {
                    let mut __size = 0;
                    __size += starknet::core::types::Felt::cairo_serialized_size(&__rust.key);
                    __size +=
                        Vec::<starknet::core::types::Felt>::cairo_serialized_size(&__rust.value);
                    __size
                }
                fn cairo_serialize(__rust: &Self::RustType) -> Vec<starknet::core::types::Felt> {
                    let mut __out: Vec<starknet::core::types::Felt> = vec![];
                    __out.extend(starknet::core::types::Felt::cairo_serialize(&__rust.key));
                    __out.extend(Vec::<starknet::core::types::Felt>::cairo_serialize(
                        &__rust.value,
                    ));
                    __out
                }
                fn cairo_deserialize(
                    __felts: &[starknet::core::types::Felt],
                    __offset: usize,
                ) -> cainome_cairo_serde::Result<Self::RustType> {
                    let mut __offset = __offset;
                    let key = starknet::core::types::Felt::cairo_deserialize(__felts, __offset)?;
                    __offset += starknet::core::types::Felt::cairo_serialized_size(&key);
                    let value =
                        Vec::<starknet::core::types::Felt>::cairo_deserialize(__felts, __offset)?;
                    __offset += Vec::<starknet::core::types::Felt>::cairo_serialized_size(&value);
                    Ok(E1 { key, value })
                }
            }
            impl E1 {
                pub fn event_selector() -> starknet::core::types::Felt {
                    starknet::core::utils::get_selector_from_name("E1").unwrap()
                }
                pub fn event_name() -> &'static str {
                    "E1"
                }
                pub(crate) fn try_from_event(
                    from_address: starknet::core::types::Felt,
                    keys: Vec<starknet::core::types::Felt>,
                    data: Vec<starknet::core::types::Felt>,
                ) -> Result<Self, String> {
                    if keys.is_empty() {
                        return Err("Event has no key".to_string());
                    }
                    use cainome_cairo_serde::CairoSerde;
                    if keys[0]
                        == starknet::core::utils::get_selector_from_name("E1")
                            .unwrap_or_else(|_| panic!("Invalid selector for {}", "E1"))
                    {
                        let res = E1::cairo_deserialize(&data, 0).map_err(|e| {
                            format!("Could not deserialize {} event data: {:?}", "E1", e)
                        })?;
                        return Ok(res);
                    }
                    Err(format!("Could not match any event from keys {:?}", keys))
                }
            }
            impl TryFrom<starknet::core::types::EmittedEvent> for E1 {
                type Error = String;
                fn try_from(
                    event: starknet::core::types::EmittedEvent,
                ) -> Result<Self, Self::Error> {
                    Self::try_from_event(event.from_address, event.keys, event.data)
                }
            }
            impl TryFrom<starknet::core::types::Event> for E1 {
                type Error = String;
                fn try_from(event: starknet::core::types::Event) -> Result<Self, Self::Error> {
                    Self::try_from_event(event.from_address, event.keys, event.data)
                }
            }
            #[derive(Clone, Debug, PartialEq, serde::Deserialize, serde::Serialize)]
            pub enum MyEnum {
                One(u8),
                Two(u16),
                Three(u32),
                #[serde(
                    serialize_with = "cainome_cairo_serde::serialize_as_hex",
                    deserialize_with = "cainome_cairo_serde::deserialize_from_hex"
                )]
                Four(u64),
                #[serde(
                    serialize_with = "cainome_cairo_serde::serialize_as_hex",
                    deserialize_with = "cainome_cairo_serde::deserialize_from_hex"
                )]
                Five(u128),
                Six(starknet::core::types::Felt),
                Seven(i32),
                #[serde(
                    serialize_with = "cainome_cairo_serde::serialize_as_hex",
                    deserialize_with = "cainome_cairo_serde::deserialize_from_hex"
                )]
                Eight(i64),
                #[serde(
                    serialize_with = "cainome_cairo_serde::serialize_as_hex",
                    deserialize_with = "cainome_cairo_serde::deserialize_from_hex"
                )]
                Nine(i128),
                #[serde(
                    serialize_with = "cainome_cairo_serde::serialize_as_hex_t2",
                    deserialize_with = "cainome_cairo_serde::deserialize_from_hex_t2"
                )]
                Ten((u8, u128)),
                #[serde(
                    serialize_with = "cainome_cairo_serde::serialize_as_hex_t3",
                    deserialize_with = "cainome_cairo_serde::deserialize_from_hex_t3"
                )]
                Eleven((starknet::core::types::Felt, u8, u128)),
            }
            impl cainome_cairo_serde::CairoSerde for MyEnum {
                type RustType = Self;
                const SERIALIZED_SIZE: std::option::Option<usize> = std::option::Option::None;
                #[inline]
                fn cairo_serialized_size(__rust: &Self::RustType) -> usize {
                    match __rust {
                        MyEnum::One(val) => u8::cairo_serialized_size(val) + 1,
                        MyEnum::Two(val) => u16::cairo_serialized_size(val) + 1,
                        MyEnum::Three(val) => u32::cairo_serialized_size(val) + 1,
                        MyEnum::Four(val) => u64::cairo_serialized_size(val) + 1,
                        MyEnum::Five(val) => u128::cairo_serialized_size(val) + 1,
                        MyEnum::Six(val) => {
                            starknet::core::types::Felt::cairo_serialized_size(val) + 1
                        }
                        MyEnum::Seven(val) => i32::cairo_serialized_size(val) + 1,
                        MyEnum::Eight(val) => i64::cairo_serialized_size(val) + 1,
                        MyEnum::Nine(val) => i128::cairo_serialized_size(val) + 1,
                        MyEnum::Ten(val) => <(u8, u128)>::cairo_serialized_size(val) + 1,
                        MyEnum::Eleven(val) => {
                            <(starknet::core::types::Felt, u8, u128)>::cairo_serialized_size(val)
                                + 1
                        }
                        _ => 0,
                    }
                }
                fn cairo_serialize(__rust: &Self::RustType) -> Vec<starknet::core::types::Felt> {
                    match __rust {
                        MyEnum::One(val) => {
                            let mut temp = vec![];
                            temp.extend(usize::cairo_serialize(&0usize));
                            temp.extend(u8::cairo_serialize(val));
                            temp
                        }
                        MyEnum::Two(val) => {
                            let mut temp = vec![];
                            temp.extend(usize::cairo_serialize(&1usize));
                            temp.extend(u16::cairo_serialize(val));
                            temp
                        }
                        MyEnum::Three(val) => {
                            let mut temp = vec![];
                            temp.extend(usize::cairo_serialize(&2usize));
                            temp.extend(u32::cairo_serialize(val));
                            temp
                        }
                        MyEnum::Four(val) => {
                            let mut temp = vec![];
                            temp.extend(usize::cairo_serialize(&3usize));
                            temp.extend(u64::cairo_serialize(val));
                            temp
                        }
                        MyEnum::Five(val) => {
                            let mut temp = vec![];
                            temp.extend(usize::cairo_serialize(&4usize));
                            temp.extend(u128::cairo_serialize(val));
                            temp
                        }
                        MyEnum::Six(val) => {
                            let mut temp = vec![];
                            temp.extend(usize::cairo_serialize(&5usize));
                            temp.extend(starknet::core::types::Felt::cairo_serialize(val));
                            temp
                        }
                        MyEnum::Seven(val) => {
                            let mut temp = vec![];
                            temp.extend(usize::cairo_serialize(&6usize));
                            temp.extend(i32::cairo_serialize(val));
                            temp
                        }
                        MyEnum::Eight(val) => {
                            let mut temp = vec![];
                            temp.extend(usize::cairo_serialize(&7usize));
                            temp.extend(i64::cairo_serialize(val));
                            temp
                        }
                        MyEnum::Nine(val) => {
                            let mut temp = vec![];
                            temp.extend(usize::cairo_serialize(&8usize));
                            temp.extend(i128::cairo_serialize(val));
                            temp
                        }
                        MyEnum::Ten(val) => {
                            let mut temp = vec![];
                            temp.extend(usize::cairo_serialize(&9usize));
                            temp.extend(<(u8, u128)>::cairo_serialize(val));
                            temp
                        }
                        MyEnum::Eleven(val) => {
                            let mut temp = vec![];
                            temp.extend(usize::cairo_serialize(&10usize));
                            temp.extend(
                                <(starknet::core::types::Felt, u8, u128)>::cairo_serialize(val),
                            );
                            temp
                        }
                        _ => vec![],
                    }
                }
                fn cairo_deserialize(
                    __felts: &[starknet::core::types::Felt],
                    __offset: usize,
                ) -> cainome_cairo_serde::Result<Self::RustType> {
                    let __f = __felts[__offset];
                    let __index = u128::from_be_bytes(__f.to_bytes_be()[16..].try_into().unwrap());
                    match __index as usize {
                        0usize => Ok(MyEnum::One(u8::cairo_deserialize(__felts, __offset + 1)?)),
                        1usize => Ok(MyEnum::Two(u16::cairo_deserialize(__felts, __offset + 1)?)),
                        2usize => Ok(MyEnum::Three(u32::cairo_deserialize(
                            __felts,
                            __offset + 1,
                        )?)),
                        3usize => Ok(MyEnum::Four(u64::cairo_deserialize(__felts, __offset + 1)?)),
                        4usize => Ok(MyEnum::Five(u128::cairo_deserialize(
                            __felts,
                            __offset + 1,
                        )?)),
                        5usize => Ok(MyEnum::Six(starknet::core::types::Felt::cairo_deserialize(
                            __felts,
                            __offset + 1,
                        )?)),
                        6usize => Ok(MyEnum::Seven(i32::cairo_deserialize(
                            __felts,
                            __offset + 1,
                        )?)),
                        7usize => Ok(MyEnum::Eight(i64::cairo_deserialize(
                            __felts,
                            __offset + 1,
                        )?)),
                        8usize => Ok(MyEnum::Nine(i128::cairo_deserialize(
                            __felts,
                            __offset + 1,
                        )?)),
                        9usize => Ok(MyEnum::Ten(<(u8, u128)>::cairo_deserialize(
                            __felts,
                            __offset + 1,
                        )?)),
                        10usize => Ok(MyEnum::Eleven(
                            <(starknet::core::types::Felt, u8, u128)>::cairo_deserialize(
                                __felts,
                                __offset + 1,
                            )?,
                        )),
                        _ => {
                            return Err(cainome_cairo_serde::Error::Deserialize(format!(
                                "Index not handle for enum {}",
                                "MyEnum"
                            )));
                        }
                    }
                }
            }
        }
    }
}
pub mod core {
    pub mod array {
        #[derive(Clone, Debug, PartialEq, serde::Deserialize, serde::Serialize)]
        pub struct Span {
            pub snapshot: Vec<starknet::core::types::Felt>,
        }
        impl cainome_cairo_serde::CairoSerde for Span {
            type RustType = Self;
            const SERIALIZED_SIZE: std::option::Option<usize> = None;
            #[inline]
            fn cairo_serialized_size(__rust: &Self::RustType) -> usize {
                let mut __size = 0;
                __size +=
                    Vec::<starknet::core::types::Felt>::cairo_serialized_size(&__rust.snapshot);
                __size
            }
            fn cairo_serialize(__rust: &Self::RustType) -> Vec<starknet::core::types::Felt> {
                let mut __out: Vec<starknet::core::types::Felt> = vec![];
                __out.extend(Vec::<starknet::core::types::Felt>::cairo_serialize(
                    &__rust.snapshot,
                ));
                __out
            }
            fn cairo_deserialize(
                __felts: &[starknet::core::types::Felt],
                __offset: usize,
            ) -> cainome_cairo_serde::Result<Self::RustType> {
                let mut __offset = __offset;
                let snapshot =
                    Vec::<starknet::core::types::Felt>::cairo_deserialize(__felts, __offset)?;
                __offset += Vec::<starknet::core::types::Felt>::cairo_serialized_size(&snapshot);
                Ok(Span { snapshot })
            }
        }
    }
}
pub struct Structs<A: starknet::accounts::ConnectedAccount + Sync> {
    pub address: starknet::core::types::Felt,
    pub account: A,
    pub block_id: starknet::core::types::BlockId,
}
impl<A: starknet::accounts::ConnectedAccount + Sync> Structs<A> {
    pub fn new(address: starknet::core::types::Felt, account: A) -> Self {
        Self {
            address,
            account,
            block_id: starknet::core::types::BlockId::Tag(
                starknet::core::types::BlockTag::PreConfirmed,
            ),
        }
    }
    pub fn set_contract_address(&mut self, address: starknet::core::types::Felt) {
        self.address = address;
    }
    pub fn provider(&self) -> &A::Provider {
        self.account.provider()
    }
    pub fn set_block(&mut self, block_id: starknet::core::types::BlockId) {
        self.block_id = block_id;
    }
    pub fn with_block(self, block_id: starknet::core::types::BlockId) -> Self {
        Self { block_id, ..self }
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn func4(
        &self,
        _a: &crate::bindings::structs::contracts::gen::gen::MyEnum,
    ) -> cainome_cairo_serde::call::FCall<A::Provider, ()> {
        use cainome_cairo_serde::CairoSerde;
        let mut __calldata = vec![];
        __calldata
            .extend(crate::bindings::structs::contracts::gen::gen::MyEnum::cairo_serialize(_a));
        let __call = starknet::core::types::FunctionCall {
            contract_address: self.address,
            entry_point_selector: starknet::macros::selector!("func4"),
            calldata: __calldata,
        };
        cainome_cairo_serde::call::FCall::new(__call, self.provider())
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn func3(
        &self,
        _a: &crate::bindings::structs::contracts::gen::gen::PlainStruct,
    ) -> cainome_cairo_serde::call::FCall<A::Provider, ()> {
        use cainome_cairo_serde::CairoSerde;
        let mut __calldata = vec![];
        __calldata.extend(
            crate::bindings::structs::contracts::gen::gen::PlainStruct::cairo_serialize(_a),
        );
        let __call = starknet::core::types::FunctionCall {
            contract_address: self.address,
            entry_point_selector: starknet::macros::selector!("func3"),
            calldata: __calldata,
        };
        cainome_cairo_serde::call::FCall::new(__call, self.provider())
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn read(
        &self,
    ) -> cainome_cairo_serde::call::FCall<
        A::Provider,
        (starknet::core::types::Felt, starknet::core::types::Felt),
    > {
        use cainome_cairo_serde::CairoSerde;
        let mut __calldata = vec![];
        let __call = starknet::core::types::FunctionCall {
            contract_address: self.address,
            entry_point_selector: starknet::macros::selector!("read"),
            calldata: __calldata,
        };
        cainome_cairo_serde::call::FCall::new(__call, self.provider())
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn func2_getcall(
        &self,
        a: &crate::bindings::structs::contracts::gen::gen::MyStruct,
    ) -> starknet::core::types::Call {
        use cainome_cairo_serde::CairoSerde;
        let mut __calldata = vec![];
        __calldata
            .extend(crate::bindings::structs::contracts::gen::gen::MyStruct::cairo_serialize(a));
        starknet::core::types::Call {
            to: self.address,
            selector: starknet::macros::selector!("func2"),
            calldata: __calldata,
        }
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn func2(
        &self,
        a: &crate::bindings::structs::contracts::gen::gen::MyStruct,
    ) -> starknet::accounts::ExecutionV3<A> {
        let __call = self.func2_getcall(a);
        self.account.execute_v3(vec![__call])
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn func5_getcall(
        &self,
        a: &crate::bindings::structs::contracts::gen::gen::MyStructInnerGeneric,
    ) -> starknet::core::types::Call {
        use cainome_cairo_serde::CairoSerde;
        let mut __calldata = vec![];
        __calldata.extend(
            crate::bindings::structs::contracts::gen::gen::MyStructInnerGeneric::cairo_serialize(a),
        );
        starknet::core::types::Call {
            to: self.address,
            selector: starknet::macros::selector!("func5"),
            calldata: __calldata,
        }
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn func5(
        &self,
        a: &crate::bindings::structs::contracts::gen::gen::MyStructInnerGeneric,
    ) -> starknet::accounts::ExecutionV3<A> {
        let __call = self.func5_getcall(a);
        self.account.execute_v3(vec![__call])
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn func1_getcall(
        &self,
        a: &crate::bindings::structs::contracts::gen::gen::MyStruct,
    ) -> starknet::core::types::Call {
        use cainome_cairo_serde::CairoSerde;
        let mut __calldata = vec![];
        __calldata
            .extend(crate::bindings::structs::contracts::gen::gen::MyStruct::cairo_serialize(a));
        starknet::core::types::Call {
            to: self.address,
            selector: starknet::macros::selector!("func1"),
            calldata: __calldata,
        }
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn func1(
        &self,
        a: &crate::bindings::structs::contracts::gen::gen::MyStruct,
    ) -> starknet::accounts::ExecutionV3<A> {
        let __call = self.func1_getcall(a);
        self.account.execute_v3(vec![__call])
    }
    pub async fn declare(
        path: &std::path::Path,
        account: &A,
        use_blake2s_class_hash: bool,
    ) -> Result<starknet::core::types::Felt, Box<dyn std::error::Error>>
    where
        A::SignError: 'static,
    {
        use starknet_api::contract_class::compiled_class_hash::HashableCompiledClass;
        let sierra_class: cairo_lang_starknet_classes::contract_class::ContractClass =
            serde_json::from_slice::<cairo_lang_starknet_classes::contract_class::ContractClass>(
                std::fs::read(path)?.as_slice(),
            )?;
        let casm_class = cairo_lang_starknet_classes::casm_contract_class::CasmContractClass::from_contract_class(
            sierra_class,
            false,
            180000usize,
        )?;
        let hash_version = if use_blake2s_class_hash {
            starknet_api::contract_class::compiled_class_hash::HashVersion::V2
        } else {
            starknet_api::contract_class::compiled_class_hash::HashVersion::V1
        };
        let class_hash = starknet::core::types::Felt::from_bytes_be(
            &casm_class.hash(&hash_version).0.to_bytes_be(),
        );
        let contract_artifact: starknet::core::types::contract::SierraClass =
            serde_json::from_reader(std::fs::File::open(path)?)?;
        let declaration = account.declare_v3(
            std::sync::Arc::new(contract_artifact.flatten()?),
            class_hash,
        );
        let declaration_result = declaration.send().await?;
        Ok(declaration_result.class_hash)
    }
    pub async fn deploy(
        udc_selector: starknet::contract::UdcSelector,
        account: A,
        class_hash: starknet::core::types::Felt,
    ) -> Result<Self, Box<dyn std::error::Error>>
    where
        A::SignError: 'static,
    {
        use cainome_cairo_serde::CairoSerde;
        let generate_salt = true;
        let is_unique = true;
        let salt: starknet::core::types::Felt = if generate_salt {
            use rand::Rng;
            rand::rng().random::<u128>().into()
        } else {
            starknet::core::types::Felt::ZERO
        };
        let factory =
            starknet::contract::ContractFactory::new_with_udc(class_hash, &account, udc_selector);
        let deployment = factory.deploy_v3(vec![], salt, is_unique);
        let deployed_address = deployment.deployed_address();
        let tx = deployment.send().await?;
        Ok(Self::new(deployed_address, account))
    }
}
pub struct StructsReader<P: starknet::providers::Provider + Sync> {
    pub address: starknet::core::types::Felt,
    pub provider: P,
    pub block_id: starknet::core::types::BlockId,
}
impl<P: starknet::providers::Provider + Sync> StructsReader<P> {
    pub fn new(address: starknet::core::types::Felt, provider: P) -> Self {
        Self {
            address,
            provider,
            block_id: starknet::core::types::BlockId::Tag(
                starknet::core::types::BlockTag::PreConfirmed,
            ),
        }
    }
    pub fn set_contract_address(&mut self, address: starknet::core::types::Felt) {
        self.address = address;
    }
    pub fn provider(&self) -> &P {
        &self.provider
    }
    pub fn set_block(&mut self, block_id: starknet::core::types::BlockId) {
        self.block_id = block_id;
    }
    pub fn with_block(self, block_id: starknet::core::types::BlockId) -> Self {
        Self { block_id, ..self }
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn func4(
        &self,
        _a: &crate::bindings::structs::contracts::gen::gen::MyEnum,
    ) -> cainome_cairo_serde::call::FCall<P, ()> {
        use cainome_cairo_serde::CairoSerde;
        let mut __calldata = vec![];
        __calldata
            .extend(crate::bindings::structs::contracts::gen::gen::MyEnum::cairo_serialize(_a));
        let __call = starknet::core::types::FunctionCall {
            contract_address: self.address,
            entry_point_selector: starknet::macros::selector!("func4"),
            calldata: __calldata,
        };
        cainome_cairo_serde::call::FCall::new(__call, self.provider())
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn func3(
        &self,
        _a: &crate::bindings::structs::contracts::gen::gen::PlainStruct,
    ) -> cainome_cairo_serde::call::FCall<P, ()> {
        use cainome_cairo_serde::CairoSerde;
        let mut __calldata = vec![];
        __calldata.extend(
            crate::bindings::structs::contracts::gen::gen::PlainStruct::cairo_serialize(_a),
        );
        let __call = starknet::core::types::FunctionCall {
            contract_address: self.address,
            entry_point_selector: starknet::macros::selector!("func3"),
            calldata: __calldata,
        };
        cainome_cairo_serde::call::FCall::new(__call, self.provider())
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn read(
        &self,
    ) -> cainome_cairo_serde::call::FCall<
        P,
        (starknet::core::types::Felt, starknet::core::types::Felt),
    > {
        use cainome_cairo_serde::CairoSerde;
        let mut __calldata = vec![];
        let __call = starknet::core::types::FunctionCall {
            contract_address: self.address,
            entry_point_selector: starknet::macros::selector!("read"),
            calldata: __calldata,
        };
        cainome_cairo_serde::call::FCall::new(__call, self.provider())
    }
}
