// ****
// Auto-generated by cainome do not edit.
// ****

#![allow(clippy::all)]
#![allow(warnings)]

pub mod contracts {
    pub mod abicov {
        pub mod structs {
            pub mod structs {
                #[derive(serde::Deserialize, serde::Serialize)]
                pub enum Event {}
                impl cainome_cairo_serde::CairoSerde for Event {
                    type RustType = Self;
                    const SERIALIZED_SIZE: std::option::Option<usize> = std::option::Option::None;
                    #[inline]
                    fn cairo_serialized_size(__rust: &Self::RustType) -> usize {
                        match __rust {
                            _ => 0,
                        }
                    }
                    fn cairo_serialize(
                        __rust: &Self::RustType,
                    ) -> Vec<starknet::core::types::Felt> {
                        match __rust {
                            _ => vec![],
                        }
                    }
                    fn cairo_deserialize(
                        __felts: &[starknet::core::types::Felt],
                        __offset: usize,
                    ) -> cainome_cairo_serde::Result<Self::RustType> {
                        let __f = __felts[__offset];
                        let __index =
                            u128::from_be_bytes(__f.to_bytes_be()[16..].try_into().unwrap());
                        match __index as usize {
                            _ => {
                                return Err(cainome_cairo_serde::Error::Deserialize(format!(
                                    "Index not handle for enum {}",
                                    "Event"
                                )));
                            }
                        }
                    }
                }
                impl Event {
                    pub fn event_selector() -> starknet::core::types::Felt {
                        starknet::core::utils::get_selector_from_name("Event").unwrap()
                    }
                    pub fn event_name() -> &'static str {
                        "Event"
                    }
                    pub(crate) fn try_from_event(
                        from_address: starknet::core::types::Felt,
                        keys: Vec<starknet::core::types::Felt>,
                        data: Vec<starknet::core::types::Felt>,
                    ) -> Result<Self, String> {
                        if keys.is_empty() {
                            return Err("Event has no key".to_string());
                        }
                        use cainome_cairo_serde::CairoSerde;
                        Err(format!("Could not match any event from keys {:?}", keys))
                    }
                }
                impl TryFrom<starknet::core::types::EmittedEvent> for Event {
                    type Error = String;
                    fn try_from(
                        event: starknet::core::types::EmittedEvent,
                    ) -> Result<Self, Self::Error> {
                        Self::try_from_event(event.from_address, event.keys, event.data)
                    }
                }
                impl TryFrom<starknet::core::types::Event> for Event {
                    type Error = String;
                    fn try_from(event: starknet::core::types::Event) -> Result<Self, Self::Error> {
                        Self::try_from_event(event.from_address, event.keys, event.data)
                    }
                }
            }
            #[derive(serde::Deserialize, serde::Serialize)]
            pub struct GenericOne {
                pub a: starknet::core::types::Felt,
                pub b: starknet::core::types::Felt,
                pub c: cainome_cairo_serde::U256,
            }
            impl cainome_cairo_serde::CairoSerde for GenericOne {
                type RustType = Self;
                const SERIALIZED_SIZE: std::option::Option<usize> = None;
                #[inline]
                fn cairo_serialized_size(__rust: &Self::RustType) -> usize {
                    let mut __size = 0;
                    __size += starknet::core::types::Felt::cairo_serialized_size(&__rust.a);
                    __size += starknet::core::types::Felt::cairo_serialized_size(&__rust.b);
                    __size += cainome_cairo_serde::U256::cairo_serialized_size(&__rust.c);
                    __size
                }
                fn cairo_serialize(__rust: &Self::RustType) -> Vec<starknet::core::types::Felt> {
                    let mut __out: Vec<starknet::core::types::Felt> = vec![];
                    __out.extend(starknet::core::types::Felt::cairo_serialize(&__rust.a));
                    __out.extend(starknet::core::types::Felt::cairo_serialize(&__rust.b));
                    __out.extend(cainome_cairo_serde::U256::cairo_serialize(&__rust.c));
                    __out
                }
                fn cairo_deserialize(
                    __felts: &[starknet::core::types::Felt],
                    __offset: usize,
                ) -> cainome_cairo_serde::Result<Self::RustType> {
                    let mut __offset = __offset;
                    let a = starknet::core::types::Felt::cairo_deserialize(__felts, __offset)?;
                    __offset += starknet::core::types::Felt::cairo_serialized_size(&a);
                    let b = starknet::core::types::Felt::cairo_deserialize(__felts, __offset)?;
                    __offset += starknet::core::types::Felt::cairo_serialized_size(&b);
                    let c = cainome_cairo_serde::U256::cairo_deserialize(__felts, __offset)?;
                    __offset += cainome_cairo_serde::U256::cairo_serialized_size(&c);
                    Ok(GenericOne { a, b, c })
                }
            }
            #[derive(serde::Deserialize, serde::Serialize)]
            pub struct ToAlias {
                pub a: u32,
            }
            impl cainome_cairo_serde::CairoSerde for ToAlias {
                type RustType = Self;
                const SERIALIZED_SIZE: std::option::Option<usize> = None;
                #[inline]
                fn cairo_serialized_size(__rust: &Self::RustType) -> usize {
                    let mut __size = 0;
                    __size += u32::cairo_serialized_size(&__rust.a);
                    __size
                }
                fn cairo_serialize(__rust: &Self::RustType) -> Vec<starknet::core::types::Felt> {
                    let mut __out: Vec<starknet::core::types::Felt> = vec![];
                    __out.extend(u32::cairo_serialize(&__rust.a));
                    __out
                }
                fn cairo_deserialize(
                    __felts: &[starknet::core::types::Felt],
                    __offset: usize,
                ) -> cainome_cairo_serde::Result<Self::RustType> {
                    let mut __offset = __offset;
                    let a = u32::cairo_deserialize(__felts, __offset)?;
                    __offset += u32::cairo_serialized_size(&a);
                    Ok(ToAlias { a })
                }
            }
            #[derive(serde::Deserialize, serde::Serialize)]
            pub struct GenericTwo {
                pub a: starknet::core::types::Felt,
                #[serde(
                    serialize_with = "cainome_cairo_serde::serialize_as_hex",
                    deserialize_with = "cainome_cairo_serde::deserialize_from_hex"
                )]
                pub b: u64,
                pub c: starknet::core::types::Felt,
                pub d: crate::bindings::substitutions::contracts::abicov::structs::ToAlias,
                pub e: Vec<crate::bindings::substitutions::contracts::abicov::structs::ToAlias>,
                pub f: crate::bindings::substitutions::contracts::abicov::structs::GenericOne,
            }
            impl cainome_cairo_serde::CairoSerde for GenericTwo {
                type RustType = Self;
                const SERIALIZED_SIZE: std::option::Option<usize> = None;
                #[inline]
                fn cairo_serialized_size(__rust: &Self::RustType) -> usize {
                    let mut __size = 0;
                    __size += starknet::core::types::Felt::cairo_serialized_size(&__rust.a);
                    __size += u64::cairo_serialized_size(&__rust.b);
                    __size += starknet::core::types::Felt::cairo_serialized_size(&__rust.c);
                    __size
                        += crate::bindings::substitutions::contracts::abicov::structs::ToAlias::cairo_serialized_size(
                            &__rust.d,
                        );
                    __size += Vec::<
                        crate::bindings::substitutions::contracts::abicov::structs::ToAlias,
                    >::cairo_serialized_size(&__rust.e);
                    __size
                        += crate::bindings::substitutions::contracts::abicov::structs::GenericOne::cairo_serialized_size(
                            &__rust.f,
                        );
                    __size
                }
                fn cairo_serialize(__rust: &Self::RustType) -> Vec<starknet::core::types::Felt> {
                    let mut __out: Vec<starknet::core::types::Felt> = vec![];
                    __out.extend(starknet::core::types::Felt::cairo_serialize(&__rust.a));
                    __out.extend(u64::cairo_serialize(&__rust.b));
                    __out.extend(starknet::core::types::Felt::cairo_serialize(&__rust.c));
                    __out
                        .extend(
                            crate::bindings::substitutions::contracts::abicov::structs::ToAlias::cairo_serialize(
                                &__rust.d,
                            ),
                        );
                    __out.extend(Vec::<
                        crate::bindings::substitutions::contracts::abicov::structs::ToAlias,
                    >::cairo_serialize(&__rust.e));
                    __out
                        .extend(
                            crate::bindings::substitutions::contracts::abicov::structs::GenericOne::cairo_serialize(
                                &__rust.f,
                            ),
                        );
                    __out
                }
                fn cairo_deserialize(
                    __felts: &[starknet::core::types::Felt],
                    __offset: usize,
                ) -> cainome_cairo_serde::Result<Self::RustType> {
                    let mut __offset = __offset;
                    let a = starknet::core::types::Felt::cairo_deserialize(__felts, __offset)?;
                    __offset += starknet::core::types::Felt::cairo_serialized_size(&a);
                    let b = u64::cairo_deserialize(__felts, __offset)?;
                    __offset += u64::cairo_serialized_size(&b);
                    let c = starknet::core::types::Felt::cairo_deserialize(__felts, __offset)?;
                    __offset += starknet::core::types::Felt::cairo_serialized_size(&c);
                    let d = crate::bindings::substitutions::contracts::abicov::structs::ToAlias::cairo_deserialize(
                        __felts,
                        __offset,
                    )?;
                    __offset
                        += crate::bindings::substitutions::contracts::abicov::structs::ToAlias::cairo_serialized_size(
                            &d,
                        );
                    let e = Vec::<
                        crate::bindings::substitutions::contracts::abicov::structs::ToAlias,
                    >::cairo_deserialize(__felts, __offset)?;
                    __offset += Vec::<
                        crate::bindings::substitutions::contracts::abicov::structs::ToAlias,
                    >::cairo_serialized_size(&e);
                    let f = crate::bindings::substitutions::contracts::abicov::structs::GenericOne::cairo_deserialize(
                        __felts,
                        __offset,
                    )?;
                    __offset
                        += crate::bindings::substitutions::contracts::abicov::structs::GenericOne::cairo_serialized_size(
                            &f,
                        );
                    Ok(GenericTwo { a, b, c, d, e, f })
                }
            }
            #[derive(serde::Deserialize, serde::Serialize)]
            pub struct Simple {
                pub felt: starknet::core::types::Felt,
                pub uint256: cainome_cairo_serde::U256,
                #[serde(
                    serialize_with = "cainome_cairo_serde::serialize_as_hex",
                    deserialize_with = "cainome_cairo_serde::deserialize_from_hex"
                )]
                pub uint64: u64,
                pub address: cainome_cairo_serde::ContractAddress,
                pub class_hash: cainome_cairo_serde::ClassHash,
                pub eth_address: cainome_cairo_serde::EthAddress,
                pub tuple: (starknet::core::types::Felt, cainome_cairo_serde::U256),
                pub span: Vec<starknet::core::types::Felt>,
            }
            impl cainome_cairo_serde::CairoSerde for Simple {
                type RustType = Self;
                const SERIALIZED_SIZE: std::option::Option<usize> = None;
                #[inline]
                fn cairo_serialized_size(__rust: &Self::RustType) -> usize {
                    let mut __size = 0;
                    __size += starknet::core::types::Felt::cairo_serialized_size(&__rust.felt);
                    __size += cainome_cairo_serde::U256::cairo_serialized_size(&__rust.uint256);
                    __size += u64::cairo_serialized_size(&__rust.uint64);
                    __size += cainome_cairo_serde::ContractAddress::cairo_serialized_size(
                        &__rust.address,
                    );
                    __size +=
                        cainome_cairo_serde::ClassHash::cairo_serialized_size(&__rust.class_hash);
                    __size +=
                        cainome_cairo_serde::EthAddress::cairo_serialized_size(&__rust.eth_address);
                    __size
                        += <(
                            starknet::core::types::Felt,
                            cainome_cairo_serde::U256,
                        )>::cairo_serialized_size(&__rust.tuple);
                    __size +=
                        Vec::<starknet::core::types::Felt>::cairo_serialized_size(&__rust.span);
                    __size
                }
                fn cairo_serialize(__rust: &Self::RustType) -> Vec<starknet::core::types::Felt> {
                    let mut __out: Vec<starknet::core::types::Felt> = vec![];
                    __out.extend(starknet::core::types::Felt::cairo_serialize(&__rust.felt));
                    __out.extend(cainome_cairo_serde::U256::cairo_serialize(&__rust.uint256));
                    __out.extend(u64::cairo_serialize(&__rust.uint64));
                    __out.extend(cainome_cairo_serde::ContractAddress::cairo_serialize(
                        &__rust.address,
                    ));
                    __out.extend(cainome_cairo_serde::ClassHash::cairo_serialize(
                        &__rust.class_hash,
                    ));
                    __out.extend(cainome_cairo_serde::EthAddress::cairo_serialize(
                        &__rust.eth_address,
                    ));
                    __out.extend(
                        <(starknet::core::types::Felt, cainome_cairo_serde::U256)>::cairo_serialize(
                            &__rust.tuple,
                        ),
                    );
                    __out.extend(Vec::<starknet::core::types::Felt>::cairo_serialize(
                        &__rust.span,
                    ));
                    __out
                }
                fn cairo_deserialize(
                    __felts: &[starknet::core::types::Felt],
                    __offset: usize,
                ) -> cainome_cairo_serde::Result<Self::RustType> {
                    let mut __offset = __offset;
                    let felt = starknet::core::types::Felt::cairo_deserialize(__felts, __offset)?;
                    __offset += starknet::core::types::Felt::cairo_serialized_size(&felt);
                    let uint256 = cainome_cairo_serde::U256::cairo_deserialize(__felts, __offset)?;
                    __offset += cainome_cairo_serde::U256::cairo_serialized_size(&uint256);
                    let uint64 = u64::cairo_deserialize(__felts, __offset)?;
                    __offset += u64::cairo_serialized_size(&uint64);
                    let address =
                        cainome_cairo_serde::ContractAddress::cairo_deserialize(__felts, __offset)?;
                    __offset +=
                        cainome_cairo_serde::ContractAddress::cairo_serialized_size(&address);
                    let class_hash =
                        cainome_cairo_serde::ClassHash::cairo_deserialize(__felts, __offset)?;
                    __offset += cainome_cairo_serde::ClassHash::cairo_serialized_size(&class_hash);
                    let eth_address =
                        cainome_cairo_serde::EthAddress::cairo_deserialize(__felts, __offset)?;
                    __offset +=
                        cainome_cairo_serde::EthAddress::cairo_serialized_size(&eth_address);
                    let tuple = <(
                        starknet::core::types::Felt,
                        cainome_cairo_serde::U256,
                    )>::cairo_deserialize(__felts, __offset)?;
                    __offset
                        += <(
                            starknet::core::types::Felt,
                            cainome_cairo_serde::U256,
                        )>::cairo_serialized_size(&tuple);
                    let span =
                        Vec::<starknet::core::types::Felt>::cairo_deserialize(__felts, __offset)?;
                    __offset += Vec::<starknet::core::types::Felt>::cairo_serialized_size(&span);
                    Ok(Simple {
                        felt,
                        uint256,
                        uint64,
                        address,
                        class_hash,
                        eth_address,
                        tuple,
                        span,
                    })
                }
            }
            #[derive(serde::Deserialize, serde::Serialize)]
            pub struct StructWithStruct {
                pub simple: crate::bindings::substitutions::contracts::abicov::structs::Simple,
            }
            impl cainome_cairo_serde::CairoSerde for StructWithStruct {
                type RustType = Self;
                const SERIALIZED_SIZE: std::option::Option<usize> = None;
                #[inline]
                fn cairo_serialized_size(__rust: &Self::RustType) -> usize {
                    let mut __size = 0;
                    __size
                        += crate::bindings::substitutions::contracts::abicov::structs::Simple::cairo_serialized_size(
                            &__rust.simple,
                        );
                    __size
                }
                fn cairo_serialize(__rust: &Self::RustType) -> Vec<starknet::core::types::Felt> {
                    let mut __out: Vec<starknet::core::types::Felt> = vec![];
                    __out
                        .extend(
                            crate::bindings::substitutions::contracts::abicov::structs::Simple::cairo_serialize(
                                &__rust.simple,
                            ),
                        );
                    __out
                }
                fn cairo_deserialize(
                    __felts: &[starknet::core::types::Felt],
                    __offset: usize,
                ) -> cainome_cairo_serde::Result<Self::RustType> {
                    let mut __offset = __offset;
                    let simple = crate::bindings::substitutions::contracts::abicov::structs::Simple::cairo_deserialize(
                        __felts,
                        __offset,
                    )?;
                    __offset
                        += crate::bindings::substitutions::contracts::abicov::structs::Simple::cairo_serialized_size(
                            &simple,
                        );
                    Ok(StructWithStruct { simple })
                }
            }
        }
    }
}
pub mod core {
    pub mod array {
        #[derive(serde::Deserialize, serde::Serialize)]
        pub struct Span {
            pub snapshot: Vec<crate::bindings::substitutions::contracts::abicov::structs::ToAlias>,
        }
        impl cainome_cairo_serde::CairoSerde for Span {
            type RustType = Self;
            const SERIALIZED_SIZE: std::option::Option<usize> = None;
            #[inline]
            fn cairo_serialized_size(__rust: &Self::RustType) -> usize {
                let mut __size = 0;
                __size
                    += Vec::<
                        crate::bindings::substitutions::contracts::abicov::structs::ToAlias,
                    >::cairo_serialized_size(&__rust.snapshot);
                __size
            }
            fn cairo_serialize(__rust: &Self::RustType) -> Vec<starknet::core::types::Felt> {
                let mut __out: Vec<starknet::core::types::Felt> = vec![];
                __out.extend(Vec::<
                    crate::bindings::substitutions::contracts::abicov::structs::ToAlias,
                >::cairo_serialize(&__rust.snapshot));
                __out
            }
            fn cairo_deserialize(
                __felts: &[starknet::core::types::Felt],
                __offset: usize,
            ) -> cainome_cairo_serde::Result<Self::RustType> {
                let mut __offset = __offset;
                let snapshot = Vec::<
                    crate::bindings::substitutions::contracts::abicov::structs::ToAlias,
                >::cairo_deserialize(__felts, __offset)?;
                __offset += Vec::<
                    crate::bindings::substitutions::contracts::abicov::structs::ToAlias,
                >::cairo_serialized_size(&snapshot);
                Ok(Span { snapshot })
            }
        }
    }
    pub mod option {
        #[derive(serde::Deserialize, serde::Serialize)]
        pub enum Option {
            Some(crate::bindings::substitutions::contracts::abicov::structs::StructWithStruct),
            None,
        }
        impl cainome_cairo_serde::CairoSerde for Option {
            type RustType = Self;
            const SERIALIZED_SIZE: std::option::Option<usize> = std::option::Option::None;
            #[inline]
            fn cairo_serialized_size(__rust: &Self::RustType) -> usize {
                match __rust {
                    Option::Some(val) => {
                        crate::bindings::substitutions::contracts::abicov::structs::StructWithStruct::cairo_serialized_size(
                            val,
                        ) + 1
                    }
                    Option::None => 1,
                    _ => 0,
                }
            }
            fn cairo_serialize(__rust: &Self::RustType) -> Vec<starknet::core::types::Felt> {
                match __rust {
                    Option::Some(val) => {
                        let mut temp = vec![];
                        temp.extend(usize::cairo_serialize(&0usize));
                        temp.extend(
                            crate::bindings::substitutions::contracts::abicov::structs::StructWithStruct::cairo_serialize(
                                val,
                            ),
                        );
                        temp
                    }
                    Option::None => usize::cairo_serialize(&1usize),
                    _ => vec![],
                }
            }
            fn cairo_deserialize(
                __felts: &[starknet::core::types::Felt],
                __offset: usize,
            ) -> cainome_cairo_serde::Result<Self::RustType> {
                let __f = __felts[__offset];
                let __index = u128::from_be_bytes(__f.to_bytes_be()[16..].try_into().unwrap());
                match __index as usize {
                    0usize => {
                        Ok(
                            Option::Some(
                                crate::bindings::substitutions::contracts::abicov::structs::StructWithStruct::cairo_deserialize(
                                    __felts,
                                    __offset + 1,
                                )?,
                            ),
                        )
                    }
                    1usize => Ok(Option::None),
                    _ => {
                        return Err(
                            cainome_cairo_serde::Error::Deserialize(
                                format!("Index not handle for enum {}", "Option"),
                            ),
                        );
                    }
                }
            }
        }
    }
}
pub struct Substitutions<A: starknet::accounts::ConnectedAccount + Sync> {
    pub address: starknet::core::types::Felt,
    pub account: A,
    pub block_id: starknet::core::types::BlockId,
}
impl<A: starknet::accounts::ConnectedAccount + Sync> Substitutions<A> {
    pub fn new(address: starknet::core::types::Felt, account: A) -> Self {
        Self {
            address,
            account,
            block_id: starknet::core::types::BlockId::Tag(
                starknet::core::types::BlockTag::PreConfirmed,
            ),
        }
    }
    pub fn set_contract_address(&mut self, address: starknet::core::types::Felt) {
        self.address = address;
    }
    pub fn provider(&self) -> &A::Provider {
        self.account.provider()
    }
    pub fn set_block(&mut self, block_id: starknet::core::types::BlockId) {
        self.block_id = block_id;
    }
    pub fn with_block(self, block_id: starknet::core::types::BlockId) -> Self {
        Self { block_id, ..self }
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn get_generic_one(
        &self,
    ) -> cainome_cairo_serde::call::FCall<
        A::Provider,
        crate::bindings::substitutions::contracts::abicov::structs::GenericOne,
    > {
        use cainome_cairo_serde::CairoSerde;
        let mut __calldata = vec![];
        let __call = starknet::core::types::FunctionCall {
            contract_address: self.address,
            entry_point_selector: starknet::macros::selector!("get_generic_one"),
            calldata: __calldata,
        };
        cainome_cairo_serde::call::FCall::new(__call, self.provider())
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn get_struct_w_struct(
        &self,
    ) -> cainome_cairo_serde::call::FCall<
        A::Provider,
        crate::bindings::substitutions::contracts::abicov::structs::StructWithStruct,
    > {
        use cainome_cairo_serde::CairoSerde;
        let mut __calldata = vec![];
        let __call = starknet::core::types::FunctionCall {
            contract_address: self.address,
            entry_point_selector: starknet::macros::selector!("get_struct_w_struct"),
            calldata: __calldata,
        };
        cainome_cairo_serde::call::FCall::new(__call, self.provider())
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn get_tuple_of_array_generic(
        &self,
    ) -> cainome_cairo_serde::call::FCall<
        A::Provider,
        (
            Vec<crate::bindings::substitutions::contracts::abicov::structs::GenericOne>,
            Vec<starknet::core::types::Felt>,
        ),
    > {
        use cainome_cairo_serde::CairoSerde;
        let mut __calldata = vec![];
        let __call = starknet::core::types::FunctionCall {
            contract_address: self.address,
            entry_point_selector: starknet::macros::selector!("get_tuple_of_array_generic"),
            calldata: __calldata,
        };
        cainome_cairo_serde::call::FCall::new(__call, self.provider())
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn get_generic_two(
        &self,
    ) -> cainome_cairo_serde::call::FCall<
        A::Provider,
        crate::bindings::substitutions::contracts::abicov::structs::GenericTwo,
    > {
        use cainome_cairo_serde::CairoSerde;
        let mut __calldata = vec![];
        let __call = starknet::core::types::FunctionCall {
            contract_address: self.address,
            entry_point_selector: starknet::macros::selector!("get_generic_two"),
            calldata: __calldata,
        };
        cainome_cairo_serde::call::FCall::new(__call, self.provider())
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn get_simple(
        &self,
    ) -> cainome_cairo_serde::call::FCall<
        A::Provider,
        crate::bindings::substitutions::contracts::abicov::structs::Simple,
    > {
        use cainome_cairo_serde::CairoSerde;
        let mut __calldata = vec![];
        let __call = starknet::core::types::FunctionCall {
            contract_address: self.address,
            entry_point_selector: starknet::macros::selector!("get_simple"),
            calldata: __calldata,
        };
        cainome_cairo_serde::call::FCall::new(__call, self.provider())
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn get_generic_one_array(
        &self,
    ) -> cainome_cairo_serde::call::FCall<
        A::Provider,
        crate::bindings::substitutions::contracts::abicov::structs::GenericOne,
    > {
        use cainome_cairo_serde::CairoSerde;
        let mut __calldata = vec![];
        let __call = starknet::core::types::FunctionCall {
            contract_address: self.address,
            entry_point_selector: starknet::macros::selector!("get_generic_one_array"),
            calldata: __calldata,
        };
        cainome_cairo_serde::call::FCall::new(__call, self.provider())
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn set_simple_getcall(
        &self,
        simple: &crate::bindings::substitutions::contracts::abicov::structs::Simple,
    ) -> starknet::core::types::Call {
        use cainome_cairo_serde::CairoSerde;
        let mut __calldata = vec![];
        __calldata.extend(
            crate::bindings::substitutions::contracts::abicov::structs::Simple::cairo_serialize(
                simple,
            ),
        );
        starknet::core::types::Call {
            to: self.address,
            selector: starknet::macros::selector!("set_simple"),
            calldata: __calldata,
        }
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn set_simple(
        &self,
        simple: &crate::bindings::substitutions::contracts::abicov::structs::Simple,
    ) -> starknet::accounts::ExecutionV3<A> {
        let __call = self.set_simple_getcall(simple);
        self.account.execute_v3(vec![__call])
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn set_tuple_generic_getcall(
        &self,
        value: &(
            crate::bindings::substitutions::contracts::abicov::structs::GenericOne,
            crate::bindings::substitutions::contracts::abicov::structs::GenericTwo,
        ),
    ) -> starknet::core::types::Call {
        use cainome_cairo_serde::CairoSerde;
        let mut __calldata = vec![];
        __calldata.extend(<(
            crate::bindings::substitutions::contracts::abicov::structs::GenericOne,
            crate::bindings::substitutions::contracts::abicov::structs::GenericTwo,
        )>::cairo_serialize(value));
        starknet::core::types::Call {
            to: self.address,
            selector: starknet::macros::selector!("set_tuple_generic"),
            calldata: __calldata,
        }
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn set_tuple_generic(
        &self,
        value: &(
            crate::bindings::substitutions::contracts::abicov::structs::GenericOne,
            crate::bindings::substitutions::contracts::abicov::structs::GenericTwo,
        ),
    ) -> starknet::accounts::ExecutionV3<A> {
        let __call = self.set_tuple_generic_getcall(value);
        self.account.execute_v3(vec![__call])
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn set_generic_two_2_getcall(
        &self,
        generic: &crate::bindings::substitutions::contracts::abicov::structs::GenericTwo,
    ) -> starknet::core::types::Call {
        use cainome_cairo_serde::CairoSerde;
        let mut __calldata = vec![];
        __calldata.extend(
            crate::bindings::substitutions::contracts::abicov::structs::GenericTwo::cairo_serialize(
                generic,
            ),
        );
        starknet::core::types::Call {
            to: self.address,
            selector: starknet::macros::selector!("set_generic_two_2"),
            calldata: __calldata,
        }
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn set_generic_two_2(
        &self,
        generic: &crate::bindings::substitutions::contracts::abicov::structs::GenericTwo,
    ) -> starknet::accounts::ExecutionV3<A> {
        let __call = self.set_generic_two_2_getcall(generic);
        self.account.execute_v3(vec![__call])
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn set_generic_one_getcall(
        &self,
        generic: &crate::bindings::substitutions::contracts::abicov::structs::GenericOne,
    ) -> starknet::core::types::Call {
        use cainome_cairo_serde::CairoSerde;
        let mut __calldata = vec![];
        __calldata.extend(
            crate::bindings::substitutions::contracts::abicov::structs::GenericOne::cairo_serialize(
                generic,
            ),
        );
        starknet::core::types::Call {
            to: self.address,
            selector: starknet::macros::selector!("set_generic_one"),
            calldata: __calldata,
        }
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn set_generic_one(
        &self,
        generic: &crate::bindings::substitutions::contracts::abicov::structs::GenericOne,
    ) -> starknet::accounts::ExecutionV3<A> {
        let __call = self.set_generic_one_getcall(generic);
        self.account.execute_v3(vec![__call])
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn set_from_alias_getcall(
        &self,
        value: &Vec<crate::bindings::substitutions::contracts::abicov::structs::ToAlias>,
    ) -> starknet::core::types::Call {
        use cainome_cairo_serde::CairoSerde;
        let mut __calldata = vec![];
        __calldata.extend(Vec::<
            crate::bindings::substitutions::contracts::abicov::structs::ToAlias,
        >::cairo_serialize(value));
        starknet::core::types::Call {
            to: self.address,
            selector: starknet::macros::selector!("set_from_alias"),
            calldata: __calldata,
        }
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn set_from_alias(
        &self,
        value: &Vec<crate::bindings::substitutions::contracts::abicov::structs::ToAlias>,
    ) -> starknet::accounts::ExecutionV3<A> {
        let __call = self.set_from_alias_getcall(value);
        self.account.execute_v3(vec![__call])
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn set_struct_w_struct_getcall(
        &self,
        sws: &crate::bindings::substitutions::contracts::abicov::structs::StructWithStruct,
    ) -> starknet::core::types::Call {
        use cainome_cairo_serde::CairoSerde;
        let mut __calldata = vec![];
        __calldata
            .extend(
                crate::bindings::substitutions::contracts::abicov::structs::StructWithStruct::cairo_serialize(
                    sws,
                ),
            );
        starknet::core::types::Call {
            to: self.address,
            selector: starknet::macros::selector!("set_struct_w_struct"),
            calldata: __calldata,
        }
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn set_struct_w_struct(
        &self,
        sws: &crate::bindings::substitutions::contracts::abicov::structs::StructWithStruct,
    ) -> starknet::accounts::ExecutionV3<A> {
        let __call = self.set_struct_w_struct_getcall(sws);
        self.account.execute_v3(vec![__call])
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn set_struct_w_optional_struct_getcall(
        &self,
        sws: &Option<crate::bindings::substitutions::contracts::abicov::structs::StructWithStruct>,
    ) -> starknet::core::types::Call {
        use cainome_cairo_serde::CairoSerde;
        let mut __calldata = vec![];
        __calldata.extend(Option::<
            crate::bindings::substitutions::contracts::abicov::structs::StructWithStruct,
        >::cairo_serialize(sws));
        starknet::core::types::Call {
            to: self.address,
            selector: starknet::macros::selector!("set_struct_w_optional_struct"),
            calldata: __calldata,
        }
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn set_struct_w_optional_struct(
        &self,
        sws: &Option<crate::bindings::substitutions::contracts::abicov::structs::StructWithStruct>,
    ) -> starknet::accounts::ExecutionV3<A> {
        let __call = self.set_struct_w_optional_struct_getcall(sws);
        self.account.execute_v3(vec![__call])
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn set_generic_two_getcall(
        &self,
        generic: &crate::bindings::substitutions::contracts::abicov::structs::GenericTwo,
    ) -> starknet::core::types::Call {
        use cainome_cairo_serde::CairoSerde;
        let mut __calldata = vec![];
        __calldata.extend(
            crate::bindings::substitutions::contracts::abicov::structs::GenericTwo::cairo_serialize(
                generic,
            ),
        );
        starknet::core::types::Call {
            to: self.address,
            selector: starknet::macros::selector!("set_generic_two"),
            calldata: __calldata,
        }
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn set_generic_two(
        &self,
        generic: &crate::bindings::substitutions::contracts::abicov::structs::GenericTwo,
    ) -> starknet::accounts::ExecutionV3<A> {
        let __call = self.set_generic_two_getcall(generic);
        self.account.execute_v3(vec![__call])
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn set_generic_two_0_getcall(
        &self,
        generic: &crate::bindings::substitutions::contracts::abicov::structs::GenericTwo,
    ) -> starknet::core::types::Call {
        use cainome_cairo_serde::CairoSerde;
        let mut __calldata = vec![];
        __calldata.extend(
            crate::bindings::substitutions::contracts::abicov::structs::GenericTwo::cairo_serialize(
                generic,
            ),
        );
        starknet::core::types::Call {
            to: self.address,
            selector: starknet::macros::selector!("set_generic_two_0"),
            calldata: __calldata,
        }
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn set_generic_two_0(
        &self,
        generic: &crate::bindings::substitutions::contracts::abicov::structs::GenericTwo,
    ) -> starknet::accounts::ExecutionV3<A> {
        let __call = self.set_generic_two_0_getcall(generic);
        self.account.execute_v3(vec![__call])
    }
    pub async fn declare(
        path: &std::path::Path,
        account: &A,
        use_blake2s_class_hash: bool,
    ) -> Result<starknet::core::types::Felt, Box<dyn std::error::Error>>
    where
        A::SignError: 'static,
    {
        use starknet_api::contract_class::compiled_class_hash::HashableCompiledClass;
        let sierra_class: cairo_lang_starknet_classes::contract_class::ContractClass =
            serde_json::from_slice::<cairo_lang_starknet_classes::contract_class::ContractClass>(
                std::fs::read(path)?.as_slice(),
            )?;
        let casm_class = cairo_lang_starknet_classes::casm_contract_class::CasmContractClass::from_contract_class(
            sierra_class,
            false,
            180000usize,
        )?;
        let hash_version = if use_blake2s_class_hash {
            starknet_api::contract_class::compiled_class_hash::HashVersion::V2
        } else {
            starknet_api::contract_class::compiled_class_hash::HashVersion::V1
        };
        let class_hash = starknet::core::types::Felt::from_bytes_be(
            &casm_class.hash(&hash_version).0.to_bytes_be(),
        );
        let contract_artifact: starknet::core::types::contract::SierraClass =
            serde_json::from_reader(std::fs::File::open(path)?)?;
        let declaration = account.declare_v3(
            std::sync::Arc::new(contract_artifact.flatten()?),
            class_hash,
        );
        let declaration_result = declaration.send().await?;
        Ok(declaration_result.class_hash)
    }
    pub async fn deploy(
        udc_selector: starknet::contract::UdcSelector,
        account: A,
        class_hash: starknet::core::types::Felt,
    ) -> Result<Self, Box<dyn std::error::Error>>
    where
        A::SignError: 'static,
    {
        use cainome_cairo_serde::CairoSerde;
        let generate_salt = true;
        let is_unique = true;
        let salt: starknet::core::types::Felt = if generate_salt {
            use rand::Rng;
            rand::rng().random::<u128>().into()
        } else {
            starknet::core::types::Felt::ZERO
        };
        let factory =
            starknet::contract::ContractFactory::new_with_udc(class_hash, &account, udc_selector);
        let deployment = factory.deploy_v3(vec![], salt, is_unique);
        let deployed_address = deployment.deployed_address();
        let tx = deployment.send().await?;
        Ok(Self::new(deployed_address, account))
    }
}
pub struct SubstitutionsReader<P: starknet::providers::Provider + Sync> {
    pub address: starknet::core::types::Felt,
    pub provider: P,
    pub block_id: starknet::core::types::BlockId,
}
impl<P: starknet::providers::Provider + Sync> SubstitutionsReader<P> {
    pub fn new(address: starknet::core::types::Felt, provider: P) -> Self {
        Self {
            address,
            provider,
            block_id: starknet::core::types::BlockId::Tag(
                starknet::core::types::BlockTag::PreConfirmed,
            ),
        }
    }
    pub fn set_contract_address(&mut self, address: starknet::core::types::Felt) {
        self.address = address;
    }
    pub fn provider(&self) -> &P {
        &self.provider
    }
    pub fn set_block(&mut self, block_id: starknet::core::types::BlockId) {
        self.block_id = block_id;
    }
    pub fn with_block(self, block_id: starknet::core::types::BlockId) -> Self {
        Self { block_id, ..self }
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn get_generic_one(
        &self,
    ) -> cainome_cairo_serde::call::FCall<
        P,
        crate::bindings::substitutions::contracts::abicov::structs::GenericOne,
    > {
        use cainome_cairo_serde::CairoSerde;
        let mut __calldata = vec![];
        let __call = starknet::core::types::FunctionCall {
            contract_address: self.address,
            entry_point_selector: starknet::macros::selector!("get_generic_one"),
            calldata: __calldata,
        };
        cainome_cairo_serde::call::FCall::new(__call, self.provider())
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn get_struct_w_struct(
        &self,
    ) -> cainome_cairo_serde::call::FCall<
        P,
        crate::bindings::substitutions::contracts::abicov::structs::StructWithStruct,
    > {
        use cainome_cairo_serde::CairoSerde;
        let mut __calldata = vec![];
        let __call = starknet::core::types::FunctionCall {
            contract_address: self.address,
            entry_point_selector: starknet::macros::selector!("get_struct_w_struct"),
            calldata: __calldata,
        };
        cainome_cairo_serde::call::FCall::new(__call, self.provider())
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn get_tuple_of_array_generic(
        &self,
    ) -> cainome_cairo_serde::call::FCall<
        P,
        (
            Vec<crate::bindings::substitutions::contracts::abicov::structs::GenericOne>,
            Vec<starknet::core::types::Felt>,
        ),
    > {
        use cainome_cairo_serde::CairoSerde;
        let mut __calldata = vec![];
        let __call = starknet::core::types::FunctionCall {
            contract_address: self.address,
            entry_point_selector: starknet::macros::selector!("get_tuple_of_array_generic"),
            calldata: __calldata,
        };
        cainome_cairo_serde::call::FCall::new(__call, self.provider())
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn get_generic_two(
        &self,
    ) -> cainome_cairo_serde::call::FCall<
        P,
        crate::bindings::substitutions::contracts::abicov::structs::GenericTwo,
    > {
        use cainome_cairo_serde::CairoSerde;
        let mut __calldata = vec![];
        let __call = starknet::core::types::FunctionCall {
            contract_address: self.address,
            entry_point_selector: starknet::macros::selector!("get_generic_two"),
            calldata: __calldata,
        };
        cainome_cairo_serde::call::FCall::new(__call, self.provider())
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn get_simple(
        &self,
    ) -> cainome_cairo_serde::call::FCall<
        P,
        crate::bindings::substitutions::contracts::abicov::structs::Simple,
    > {
        use cainome_cairo_serde::CairoSerde;
        let mut __calldata = vec![];
        let __call = starknet::core::types::FunctionCall {
            contract_address: self.address,
            entry_point_selector: starknet::macros::selector!("get_simple"),
            calldata: __calldata,
        };
        cainome_cairo_serde::call::FCall::new(__call, self.provider())
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn get_generic_one_array(
        &self,
    ) -> cainome_cairo_serde::call::FCall<
        P,
        crate::bindings::substitutions::contracts::abicov::structs::GenericOne,
    > {
        use cainome_cairo_serde::CairoSerde;
        let mut __calldata = vec![];
        let __call = starknet::core::types::FunctionCall {
            contract_address: self.address,
            entry_point_selector: starknet::macros::selector!("get_generic_one_array"),
            calldata: __calldata,
        };
        cainome_cairo_serde::call::FCall::new(__call, self.provider())
    }
}
