// ****
// Auto-generated by cainome do not edit.
// ****

#![allow(clippy::all)]
#![allow(warnings)]

#[derive(Debug)]
pub struct ContractDeployed {
    pub address: starknet::core::types::Felt,
    pub deployer: starknet::core::types::Felt,
    pub unique: starknet::core::types::Felt,
    pub classHash: starknet::core::types::Felt,
    pub calldata_len: starknet::core::types::Felt,
    pub calldata: cainome_cairo_serde::CairoArrayLegacy<starknet::core::types::Felt>,
    pub salt: starknet::core::types::Felt,
}
impl cainome_cairo_serde::CairoSerde for ContractDeployed {
    type RustType = Self;
    const SERIALIZED_SIZE: std::option::Option<usize> = None;
    #[inline]
    fn cairo_serialized_size(__rust: &Self::RustType) -> usize {
        let mut __size = 0;
        __size += starknet::core::types::Felt::cairo_serialized_size(&__rust.address);
        __size += starknet::core::types::Felt::cairo_serialized_size(&__rust.deployer);
        __size += starknet::core::types::Felt::cairo_serialized_size(&__rust.unique);
        __size += starknet::core::types::Felt::cairo_serialized_size(&__rust.classHash);
        __size += starknet::core::types::Felt::cairo_serialized_size(&__rust.calldata_len);
        __size
            += cainome_cairo_serde::CairoArrayLegacy::<
                starknet::core::types::Felt,
            >::cairo_serialized_size(&__rust.calldata);
        __size += starknet::core::types::Felt::cairo_serialized_size(&__rust.salt);
        __size
    }
    fn cairo_serialize(__rust: &Self::RustType) -> Vec<starknet::core::types::Felt> {
        let mut __out: Vec<starknet::core::types::Felt> = vec![];
        __out.extend(starknet::core::types::Felt::cairo_serialize(
            &__rust.address,
        ));
        __out.extend(starknet::core::types::Felt::cairo_serialize(
            &__rust.deployer,
        ));
        __out.extend(starknet::core::types::Felt::cairo_serialize(&__rust.unique));
        __out.extend(starknet::core::types::Felt::cairo_serialize(
            &__rust.classHash,
        ));
        __out.extend(starknet::core::types::Felt::cairo_serialize(
            &__rust.calldata_len,
        ));
        __out.extend(cainome_cairo_serde::CairoArrayLegacy::<
            starknet::core::types::Felt,
        >::cairo_serialize(&__rust.calldata));
        __out.extend(starknet::core::types::Felt::cairo_serialize(&__rust.salt));
        __out
    }
    fn cairo_deserialize(
        __felts: &[starknet::core::types::Felt],
        __offset: usize,
    ) -> cainome_cairo_serde::Result<Self::RustType> {
        let mut __offset = __offset;
        let address = starknet::core::types::Felt::cairo_deserialize(__felts, __offset)?;
        __offset += starknet::core::types::Felt::cairo_serialized_size(&address);
        let deployer = starknet::core::types::Felt::cairo_deserialize(__felts, __offset)?;
        __offset += starknet::core::types::Felt::cairo_serialized_size(&deployer);
        let unique = starknet::core::types::Felt::cairo_deserialize(__felts, __offset)?;
        __offset += starknet::core::types::Felt::cairo_serialized_size(&unique);
        let classHash = starknet::core::types::Felt::cairo_deserialize(__felts, __offset)?;
        __offset += starknet::core::types::Felt::cairo_serialized_size(&classHash);
        let calldata_len = starknet::core::types::Felt::cairo_deserialize(__felts, __offset)?;
        __offset += starknet::core::types::Felt::cairo_serialized_size(&calldata_len);
        let calldata = cainome_cairo_serde::CairoArrayLegacy::<
            starknet::core::types::Felt,
        >::cairo_deserialize(__felts, __offset)?;
        __offset
            += cainome_cairo_serde::CairoArrayLegacy::<
                starknet::core::types::Felt,
            >::cairo_serialized_size(&calldata);
        let salt = starknet::core::types::Felt::cairo_deserialize(__felts, __offset)?;
        __offset += starknet::core::types::Felt::cairo_serialized_size(&salt);
        Ok(ContractDeployed {
            address,
            deployer,
            unique,
            classHash,
            calldata_len,
            calldata,
            salt,
        })
    }
}
impl ContractDeployed {
    pub fn event_selector() -> starknet::core::types::Felt {
        starknet::core::utils::get_selector_from_name("ContractDeployed").unwrap()
    }
    pub fn event_name() -> &'static str {
        "ContractDeployed"
    }
    pub(crate) fn try_from_event(
        from_address: starknet::core::types::Felt,
        keys: Vec<starknet::core::types::Felt>,
        data: Vec<starknet::core::types::Felt>,
    ) -> Result<Self, String> {
        if keys.is_empty() {
            return Err("Event has no key".to_string());
        }
        use cainome_cairo_serde::CairoSerde;
        if keys[0]
            == starknet::core::utils::get_selector_from_name("ContractDeployed")
                .unwrap_or_else(|_| panic!("Invalid selector for {}", "ContractDeployed"))
        {
            let res = ContractDeployed::cairo_deserialize(&data, 0).map_err(|e| {
                format!(
                    "Could not deserialize {} event data: {:?}",
                    "ContractDeployed", e
                )
            })?;
            return Ok(res);
        }
        Err(format!("Could not match any event from keys {:?}", keys))
    }
}
impl TryFrom<starknet::core::types::EmittedEvent> for ContractDeployed {
    type Error = String;
    fn try_from(event: starknet::core::types::EmittedEvent) -> Result<Self, Self::Error> {
        Self::try_from_event(event.from_address, event.keys, event.data)
    }
}
impl TryFrom<starknet::core::types::Event> for ContractDeployed {
    type Error = String;
    fn try_from(event: starknet::core::types::Event) -> Result<Self, Self::Error> {
        Self::try_from_event(event.from_address, event.keys, event.data)
    }
}
pub struct UDC<A: starknet::accounts::ConnectedAccount + Sync> {
    pub address: starknet::core::types::Felt,
    pub account: A,
    pub block_id: starknet::core::types::BlockId,
}
impl<A: starknet::accounts::ConnectedAccount + Sync> UDC<A> {
    pub fn new(address: starknet::core::types::Felt, account: A) -> Self {
        Self {
            address,
            account,
            block_id: starknet::core::types::BlockId::Tag(
                starknet::core::types::BlockTag::PreConfirmed,
            ),
        }
    }
    pub fn set_contract_address(&mut self, address: starknet::core::types::Felt) {
        self.address = address;
    }
    pub fn provider(&self) -> &A::Provider {
        self.account.provider()
    }
    pub fn set_block(&mut self, block_id: starknet::core::types::BlockId) {
        self.block_id = block_id;
    }
    pub fn with_block(self, block_id: starknet::core::types::BlockId) -> Self {
        Self { block_id, ..self }
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn deployContract_getcall(
        &self,
        classHash: &starknet::core::types::Felt,
        salt: &starknet::core::types::Felt,
        unique: &starknet::core::types::Felt,
        calldata_len: &starknet::core::types::Felt,
        calldata: &cainome_cairo_serde::CairoArrayLegacy<starknet::core::types::Felt>,
    ) -> starknet::core::types::Call {
        use cainome_cairo_serde::CairoSerde;
        let mut __calldata = vec![];
        __calldata.extend(starknet::core::types::Felt::cairo_serialize(classHash));
        __calldata.extend(starknet::core::types::Felt::cairo_serialize(salt));
        __calldata.extend(starknet::core::types::Felt::cairo_serialize(unique));
        __calldata.extend(starknet::core::types::Felt::cairo_serialize(calldata_len));
        __calldata.extend(cainome_cairo_serde::CairoArrayLegacy::<
            starknet::core::types::Felt,
        >::cairo_serialize(calldata));
        starknet::core::types::Call {
            to: self.address,
            selector: starknet::macros::selector!("deployContract"),
            calldata: __calldata,
        }
    }
    #[allow(clippy::ptr_arg)]
    #[allow(clippy::too_many_arguments)]
    pub fn deployContract(
        &self,
        classHash: &starknet::core::types::Felt,
        salt: &starknet::core::types::Felt,
        unique: &starknet::core::types::Felt,
        calldata_len: &starknet::core::types::Felt,
        calldata: &cainome_cairo_serde::CairoArrayLegacy<starknet::core::types::Felt>,
    ) -> starknet::accounts::ExecutionV3<A> {
        let __call = self.deployContract_getcall(classHash, salt, unique, calldata_len, calldata);
        self.account.execute_v3(vec![__call])
    }
    pub async fn declare(
        path: &std::path::Path,
        account: &A,
        use_blake2s_class_hash: bool,
    ) -> Result<starknet::core::types::Felt, Box<dyn std::error::Error>>
    where
        A::SignError: 'static,
    {
        use starknet_api::contract_class::compiled_class_hash::HashableCompiledClass;
        let sierra_class: cairo_lang_starknet_classes::contract_class::ContractClass =
            serde_json::from_slice::<cairo_lang_starknet_classes::contract_class::ContractClass>(
                std::fs::read(path)?.as_slice(),
            )?;
        let casm_class = cairo_lang_starknet_classes::casm_contract_class::CasmContractClass::from_contract_class(
            sierra_class,
            false,
            180000usize,
        )?;
        let hash_version = if use_blake2s_class_hash {
            starknet_api::contract_class::compiled_class_hash::HashVersion::V2
        } else {
            starknet_api::contract_class::compiled_class_hash::HashVersion::V1
        };
        let class_hash = starknet::core::types::Felt::from_bytes_be(
            &casm_class.hash(&hash_version).0.to_bytes_be(),
        );
        let contract_artifact: starknet::core::types::contract::SierraClass =
            serde_json::from_reader(std::fs::File::open(path)?)?;
        let declaration = account.declare_v3(
            std::sync::Arc::new(contract_artifact.flatten()?),
            class_hash,
        );
        let declaration_result = declaration.send().await?;
        Ok(declaration_result.class_hash)
    }
}
pub struct UDCReader<P: starknet::providers::Provider + Sync> {
    pub address: starknet::core::types::Felt,
    pub provider: P,
    pub block_id: starknet::core::types::BlockId,
}
impl<P: starknet::providers::Provider + Sync> UDCReader<P> {
    pub fn new(address: starknet::core::types::Felt, provider: P) -> Self {
        Self {
            address,
            provider,
            block_id: starknet::core::types::BlockId::Tag(
                starknet::core::types::BlockTag::PreConfirmed,
            ),
        }
    }
    pub fn set_contract_address(&mut self, address: starknet::core::types::Felt) {
        self.address = address;
    }
    pub fn provider(&self) -> &P {
        &self.provider
    }
    pub fn set_block(&mut self, block_id: starknet::core::types::BlockId) {
        self.block_id = block_id;
    }
    pub fn with_block(self, block_id: starknet::core::types::BlockId) -> Self {
        Self { block_id, ..self }
    }
}
